// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8ae8b68aa14b

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceEvalsUpdateRequest struct {
	EvalID string `pathParam:"style=simple,explode=false,name=eval_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	Body  components.PublicEvalDefinitionUpdate     `request:"mediaType=application/json"`
}

func (a *APIPerformanceEvalsUpdateRequest) GetEvalID() string {
	if a == nil {
		return ""
	}
	return a.EvalID
}

func (a *APIPerformanceEvalsUpdateRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceEvalsUpdateRequest) GetBody() components.PublicEvalDefinitionUpdate {
	if a == nil {
		return components.PublicEvalDefinitionUpdate{}
	}
	return a.Body
}

type APIPerformanceEvalsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalDefinition *components.PublicEvalDefinition
}

func (a APIPerformanceEvalsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceEvalsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceEvalsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceEvalsUpdateResponse) GetPublicEvalDefinition() *components.PublicEvalDefinition {
	if a == nil {
		return nil
	}
	return a.PublicEvalDefinition
}
