// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c4609903a67b

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceActionsRefreshResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicRefreshActionsResponse *components.PublicRefreshActionsResponse
}

func (a APIPerformanceActionsRefreshResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceActionsRefreshResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceActionsRefreshResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceActionsRefreshResponse) GetPublicRefreshActionsResponse() *components.PublicRefreshActionsResponse {
	if a == nil {
		return nil
	}
	return a.PublicRefreshActionsResponse
}
