// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceOperationPromptsListRequest struct {
	OperationID string `pathParam:"style=simple,explode=false,name=operation_id"`
}

func (a *APIPerformanceOperationPromptsListRequest) GetOperationID() string {
	if a == nil {
		return ""
	}
	return a.OperationID
}

type APIPerformanceOperationPromptsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseAPIPerformanceOperationPromptsList []components.PublicOperationPrompt
}

func (a APIPerformanceOperationPromptsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceOperationPromptsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceOperationPromptsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceOperationPromptsListResponse) GetResponseAPIPerformanceOperationPromptsList() []components.PublicOperationPrompt {
	if a == nil {
		return nil
	}
	return a.ResponseAPIPerformanceOperationPromptsList
}
