// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ee776e0bd7e

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
	"github.com/usesapient/cli/internal/sdk/types"
)

type APIPerformanceConfigUpdateRequest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	configScope *string                                  `const:"custom_evals" queryParam:"style=form,explode=true,name=config_scope"`
	Body        components.PublicEvalConfigUpdateRequest `request:"mediaType=application/json"`
}

func (a APIPerformanceConfigUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigUpdateRequest) GetConfigScope() *string {
	return types.Pointer("custom_evals")
}

func (a *APIPerformanceConfigUpdateRequest) GetBody() components.PublicEvalConfigUpdateRequest {
	if a == nil {
		return components.PublicEvalConfigUpdateRequest{}
	}
	return a.Body
}

type APIPerformanceConfigUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalConfigResponse *components.PublicEvalConfigResponse
}

func (a APIPerformanceConfigUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceConfigUpdateResponse) GetPublicEvalConfigResponse() *components.PublicEvalConfigResponse {
	if a == nil {
		return nil
	}
	return a.PublicEvalConfigResponse
}
