// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceRunsRetrieveRequest struct {
	RunID string `pathParam:"style=simple,explode=false,name=run_id"`
}

func (a *APIPerformanceRunsRetrieveRequest) GetRunID() string {
	if a == nil {
		return ""
	}
	return a.RunID
}

type APIPerformanceRunsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceRunResponse *components.PublicAPIPerformanceRunResponse
}

func (a APIPerformanceRunsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceRunsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceRunsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceRunsRetrieveResponse) GetPublicAPIPerformanceRunResponse() *components.PublicAPIPerformanceRunResponse {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceRunResponse
}
