// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e079b53f3093

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceSourcesListRequest struct {
	IncludeSystem *bool `default:"false" queryParam:"style=form,explode=true,name=include_system"`
}

func (a APIPerformanceSourcesListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceSourcesListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceSourcesListRequest) GetIncludeSystem() *bool {
	if a == nil {
		return nil
	}
	return a.IncludeSystem
}

type APIPerformanceSourcesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceSourcesResponse *components.PublicAPIPerformanceSourcesResponse
}

func (a APIPerformanceSourcesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceSourcesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceSourcesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceSourcesListResponse) GetPublicAPIPerformanceSourcesResponse() *components.PublicAPIPerformanceSourcesResponse {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceSourcesResponse
}
