// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceRunsListRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	Since optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=since"`
	Limit *int64                                    `default:"20" queryParam:"style=form,explode=true,name=limit"`
}

func (a APIPerformanceRunsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceRunsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceRunsListRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceRunsListRequest) GetSince() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Since
}

func (a *APIPerformanceRunsListRequest) GetLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.Limit
}

type APIPerformanceRunsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvalRunsListResponse *components.EvalRunsListResponse
}

func (a APIPerformanceRunsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceRunsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceRunsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceRunsListResponse) GetEvalRunsListResponse() *components.EvalRunsListResponse {
	if a == nil {
		return nil
	}
	return a.EvalRunsListResponse
}
