// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bdd86456350a

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceStarterProjectsDeleteRequest struct {
	StarterProjectID string `pathParam:"style=simple,explode=false,name=starter_project_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
}

func (a *APIPerformanceStarterProjectsDeleteRequest) GetStarterProjectID() string {
	if a == nil {
		return ""
	}
	return a.StarterProjectID
}

func (a *APIPerformanceStarterProjectsDeleteRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

type APIPerformanceStarterProjectsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicStartingProject *components.PublicStartingProject
}

func (a APIPerformanceStarterProjectsDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceStarterProjectsDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceStarterProjectsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceStarterProjectsDeleteResponse) GetPublicStartingProject() *components.PublicStartingProject {
	if a == nil {
		return nil
	}
	return a.PublicStartingProject
}
