// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceEvaluationConfigRetrieveRequest struct {
	InterfaceID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=interface_id"`
}

func (a *APIPerformanceEvaluationConfigRetrieveRequest) GetInterfaceID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.InterfaceID
}

type APIPerformanceEvaluationConfigRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceEvaluationConfig *components.PublicAPIPerformanceEvaluationConfig
}

func (a APIPerformanceEvaluationConfigRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceEvaluationConfigRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceEvaluationConfigRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceEvaluationConfigRetrieveResponse) GetPublicAPIPerformanceEvaluationConfig() *components.PublicAPIPerformanceEvaluationConfig {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceEvaluationConfig
}
