// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceUseCasesUpdateRequest struct {
	UseCaseID string                                              `pathParam:"style=simple,explode=false,name=use_case_id"`
	Body      components.UpdatePublicAPIPerformanceUseCaseRequest `request:"mediaType=application/json"`
}

func (a *APIPerformanceUseCasesUpdateRequest) GetUseCaseID() string {
	if a == nil {
		return ""
	}
	return a.UseCaseID
}

func (a *APIPerformanceUseCasesUpdateRequest) GetBody() components.UpdatePublicAPIPerformanceUseCaseRequest {
	if a == nil {
		return components.UpdatePublicAPIPerformanceUseCaseRequest{}
	}
	return a.Body
}

type APIPerformanceUseCasesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceUseCase *components.PublicAPIPerformanceUseCase
}

func (a APIPerformanceUseCasesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceUseCasesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceUseCasesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceUseCasesUpdateResponse) GetPublicAPIPerformanceUseCase() *components.PublicAPIPerformanceUseCase {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceUseCase
}
