// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformancePlatformsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformancePlatformsResponse *components.PublicAPIPerformancePlatformsResponse
}

func (a APIPerformancePlatformsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformancePlatformsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformancePlatformsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformancePlatformsListResponse) GetPublicAPIPerformancePlatformsResponse() *components.PublicAPIPerformancePlatformsResponse {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformancePlatformsResponse
}
