// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceOperationsListRequest struct {
	CategoryID  optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=category_id"`
	InterfaceID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=interface_id"`
}

func (a *APIPerformanceOperationsListRequest) GetCategoryID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.CategoryID
}

func (a *APIPerformanceOperationsListRequest) GetInterfaceID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.InterfaceID
}

type APIPerformanceOperationsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseAPIPerformanceOperationsList []components.PublicAPIPerformanceOperation
}

func (a APIPerformanceOperationsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceOperationsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceOperationsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceOperationsListResponse) GetResponseAPIPerformanceOperationsList() []components.PublicAPIPerformanceOperation {
	if a == nil {
		return nil
	}
	return a.ResponseAPIPerformanceOperationsList
}
