// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4b0aba362351

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceStarterProjectsListRequest struct {
	SourceID *string `queryParam:"style=form,explode=true,name=source_id"`
}

func (a *APIPerformanceStarterProjectsListRequest) GetSourceID() *string {
	if a == nil {
		return nil
	}
	return a.SourceID
}

type APIPerformanceStarterProjectsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicStartingProjectsResponse *components.PublicStartingProjectsResponse
}

func (a APIPerformanceStarterProjectsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceStarterProjectsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceStarterProjectsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceStarterProjectsListResponse) GetPublicStartingProjectsResponse() *components.PublicStartingProjectsResponse {
	if a == nil {
		return nil
	}
	return a.PublicStartingProjectsResponse
}
