// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cc0aa3542015

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceEvalsRetrieveRequest struct {
	EvalID string `pathParam:"style=simple,explode=false,name=eval_id"`
}

func (a *APIPerformanceEvalsRetrieveRequest) GetEvalID() string {
	if a == nil {
		return ""
	}
	return a.EvalID
}

type APIPerformanceEvalsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalDefinition *components.PublicEvalDefinition
}

func (a APIPerformanceEvalsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceEvalsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceEvalsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceEvalsRetrieveResponse) GetPublicEvalDefinition() *components.PublicEvalDefinition {
	if a == nil {
		return nil
	}
	return a.PublicEvalDefinition
}
