// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6674ba1b3cdf

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceActionsRetrieveRequest struct {
	ActionID      string `pathParam:"style=simple,explode=false,name=action_id"`
	IncludePrompt *bool  `default:"false" queryParam:"style=form,explode=true,name=include_prompt"`
}

func (a APIPerformanceActionsRetrieveRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceActionsRetrieveRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceActionsRetrieveRequest) GetActionID() string {
	if a == nil {
		return ""
	}
	return a.ActionID
}

func (a *APIPerformanceActionsRetrieveRequest) GetIncludePrompt() *bool {
	if a == nil {
		return nil
	}
	return a.IncludePrompt
}

type APIPerformanceActionsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicActionDetailResponse *components.PublicActionDetailResponse
}

func (a APIPerformanceActionsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceActionsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceActionsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceActionsRetrieveResponse) GetPublicActionDetailResponse() *components.PublicActionDetailResponse {
	if a == nil {
		return nil
	}
	return a.PublicActionDetailResponse
}
