// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceResultsRetrieveRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand            optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	IntegrationID    optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=integration_id"`
	Limit            *int64                                    `default:"20" queryParam:"style=form,explode=true,name=limit"`
	IncludeDocsAudit *bool                                     `default:"false" queryParam:"style=form,explode=true,name=include_docs_audit"`
	DocsAuditLimit   *int64                                    `default:"500" queryParam:"style=form,explode=true,name=docs_audit_limit"`
}

func (a APIPerformanceResultsRetrieveRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceResultsRetrieveRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceResultsRetrieveRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceResultsRetrieveRequest) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.IntegrationID
}

func (a *APIPerformanceResultsRetrieveRequest) GetLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.Limit
}

func (a *APIPerformanceResultsRetrieveRequest) GetIncludeDocsAudit() *bool {
	if a == nil {
		return nil
	}
	return a.IncludeDocsAudit
}

func (a *APIPerformanceResultsRetrieveRequest) GetDocsAuditLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.DocsAuditLimit
}

type APIPerformanceResultsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceResultsResponse *components.PublicAPIPerformanceResultsResponse
}

func (a APIPerformanceResultsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceResultsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceResultsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceResultsRetrieveResponse) GetPublicAPIPerformanceResultsResponse() *components.PublicAPIPerformanceResultsResponse {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceResultsResponse
}
