// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 94d59fe037b7

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceSkillsListRequest struct {
	IntegrationID *string `queryParam:"style=form,explode=true,name=integration_id"`
	SourceID      *string `queryParam:"style=form,explode=true,name=source_id"`
	Enabled       *bool   `default:"true" queryParam:"style=form,explode=true,name=enabled"`
	Stale         *bool   `default:"false" queryParam:"style=form,explode=true,name=stale"`
}

func (a APIPerformanceSkillsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceSkillsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceSkillsListRequest) GetIntegrationID() *string {
	if a == nil {
		return nil
	}
	return a.IntegrationID
}

func (a *APIPerformanceSkillsListRequest) GetSourceID() *string {
	if a == nil {
		return nil
	}
	return a.SourceID
}

func (a *APIPerformanceSkillsListRequest) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *APIPerformanceSkillsListRequest) GetStale() *bool {
	if a == nil {
		return nil
	}
	return a.Stale
}

type APIPerformanceSkillsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceSkillsResponse *components.PublicAPIPerformanceSkillsResponse
}

func (a APIPerformanceSkillsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceSkillsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceSkillsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceSkillsListResponse) GetPublicAPIPerformanceSkillsResponse() *components.PublicAPIPerformanceSkillsResponse {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceSkillsResponse
}
