// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceCustomEvalsUpdateRequest struct {
	CustomEvalID string `pathParam:"style=simple,explode=false,name=custom_eval_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	Body  components.PublicCustomEvalUpdateRequest  `request:"mediaType=application/json"`
}

func (a *APIPerformanceCustomEvalsUpdateRequest) GetCustomEvalID() string {
	if a == nil {
		return ""
	}
	return a.CustomEvalID
}

func (a *APIPerformanceCustomEvalsUpdateRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceCustomEvalsUpdateRequest) GetBody() components.PublicCustomEvalUpdateRequest {
	if a == nil {
		return components.PublicCustomEvalUpdateRequest{}
	}
	return a.Body
}

type APIPerformanceCustomEvalsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicCustomEval *components.PublicCustomEval
}

func (a APIPerformanceCustomEvalsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceCustomEvalsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceCustomEvalsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceCustomEvalsUpdateResponse) GetPublicCustomEval() *components.PublicCustomEval {
	if a == nil {
		return nil
	}
	return a.PublicCustomEval
}
