// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a7b6a3311d80

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceDiagnoseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DiagnoseEvalRunsResponse *components.DiagnoseEvalRunsResponse
}

func (a APIPerformanceDiagnoseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceDiagnoseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceDiagnoseResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceDiagnoseResponse) GetDiagnoseEvalRunsResponse() *components.DiagnoseEvalRunsResponse {
	if a == nil {
		return nil
	}
	return a.DiagnoseEvalRunsResponse
}
