// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0cba5727a218

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceCustomEvalsListRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
}

func (a *APIPerformanceCustomEvalsListRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

type APIPerformanceCustomEvalsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicCustomEvalsResponse *components.PublicCustomEvalsResponse
}

func (a APIPerformanceCustomEvalsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceCustomEvalsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceCustomEvalsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceCustomEvalsListResponse) GetPublicCustomEvalsResponse() *components.PublicCustomEvalsResponse {
	if a == nil {
		return nil
	}
	return a.PublicCustomEvalsResponse
}
