// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceUseCasesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceUseCase *components.PublicAPIPerformanceUseCase
}

func (a APIPerformanceUseCasesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceUseCasesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceUseCasesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceUseCasesCreateResponse) GetPublicAPIPerformanceUseCase() *components.PublicAPIPerformanceUseCase {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceUseCase
}
