// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fdbd3778e511

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceActionsUpdateRequest struct {
	ActionID string                               `pathParam:"style=simple,explode=false,name=action_id"`
	Body     components.PublicUpdateActionRequest `request:"mediaType=application/json"`
}

func (a *APIPerformanceActionsUpdateRequest) GetActionID() string {
	if a == nil {
		return ""
	}
	return a.ActionID
}

func (a *APIPerformanceActionsUpdateRequest) GetBody() components.PublicUpdateActionRequest {
	if a == nil {
		return components.PublicUpdateActionRequest{}
	}
	return a.Body
}

type APIPerformanceActionsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicActionDetailResponse *components.PublicActionDetailResponse
}

func (a APIPerformanceActionsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceActionsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceActionsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceActionsUpdateResponse) GetPublicActionDetailResponse() *components.PublicActionDetailResponse {
	if a == nil {
		return nil
	}
	return a.PublicActionDetailResponse
}
