// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceOperationsDeleteRequest struct {
	OperationID string `pathParam:"style=simple,explode=false,name=operation_id"`
}

func (a *APIPerformanceOperationsDeleteRequest) GetOperationID() string {
	if a == nil {
		return ""
	}
	return a.OperationID
}

type APIPerformanceOperationsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOkResponse *components.PublicOkResponse
}

func (a APIPerformanceOperationsDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceOperationsDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceOperationsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceOperationsDeleteResponse) GetPublicOkResponse() *components.PublicOkResponse {
	if a == nil {
		return nil
	}
	return a.PublicOkResponse
}
