// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d6d3ef7d5d08

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceCustomEvalsDeleteRequest struct {
	CustomEvalID string `pathParam:"style=simple,explode=false,name=custom_eval_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
}

func (a *APIPerformanceCustomEvalsDeleteRequest) GetCustomEvalID() string {
	if a == nil {
		return ""
	}
	return a.CustomEvalID
}

func (a *APIPerformanceCustomEvalsDeleteRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

type APIPerformanceCustomEvalsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicCustomEval *components.PublicCustomEval
}

func (a APIPerformanceCustomEvalsDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceCustomEvalsDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceCustomEvalsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceCustomEvalsDeleteResponse) GetPublicCustomEval() *components.PublicCustomEval {
	if a == nil {
		return nil
	}
	return a.PublicCustomEval
}
