// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformancePromptsDeleteRequest struct {
	PromptID string `pathParam:"style=simple,explode=false,name=prompt_id"`
}

func (a *APIPerformancePromptsDeleteRequest) GetPromptID() string {
	if a == nil {
		return ""
	}
	return a.PromptID
}

type APIPerformancePromptsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOkResponse *components.PublicOkResponse
}

func (a APIPerformancePromptsDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformancePromptsDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformancePromptsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformancePromptsDeleteResponse) GetPublicOkResponse() *components.PublicOkResponse {
	if a == nil {
		return nil
	}
	return a.PublicOkResponse
}
