// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceConfigRetrieveRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand         optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	IntegrationID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=integration_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	configScope optionalnullable.OptionalNullable[string] `const:"custom_evals" queryParam:"style=form,explode=true,name=config_scope"`
}

func (a APIPerformanceConfigRetrieveRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigRetrieveRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigRetrieveRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceConfigRetrieveRequest) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.IntegrationID
}

func (a *APIPerformanceConfigRetrieveRequest) GetConfigScope() optionalnullable.OptionalNullable[string] {
	var tmp string = "custom_evals"
	return optionalnullable.From[string](&tmp)
}

type APIPerformanceConfigRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalConfigResponse *components.PublicEvalConfigResponse
}

func (a APIPerformanceConfigRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceConfigRetrieveResponse) GetPublicEvalConfigResponse() *components.PublicEvalConfigResponse {
	if a == nil {
		return nil
	}
	return a.PublicEvalConfigResponse
}
