// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceCustomEvalsCreateRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	Body  components.PublicCustomEvalRequest        `request:"mediaType=application/json"`
}

func (a *APIPerformanceCustomEvalsCreateRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceCustomEvalsCreateRequest) GetBody() components.PublicCustomEvalRequest {
	if a == nil {
		return components.PublicCustomEvalRequest{}
	}
	return a.Body
}

type APIPerformanceCustomEvalsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicCustomEval *components.PublicCustomEval
}

func (a APIPerformanceCustomEvalsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceCustomEvalsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceCustomEvalsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceCustomEvalsCreateResponse) GetPublicCustomEval() *components.PublicCustomEval {
	if a == nil {
		return nil
	}
	return a.PublicCustomEval
}
