// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceOperationsUpdateRequest struct {
	OperationID string                                                `pathParam:"style=simple,explode=false,name=operation_id"`
	Body        components.UpdatePublicAPIPerformanceOperationRequest `request:"mediaType=application/json"`
}

func (a *APIPerformanceOperationsUpdateRequest) GetOperationID() string {
	if a == nil {
		return ""
	}
	return a.OperationID
}

func (a *APIPerformanceOperationsUpdateRequest) GetBody() components.UpdatePublicAPIPerformanceOperationRequest {
	if a == nil {
		return components.UpdatePublicAPIPerformanceOperationRequest{}
	}
	return a.Body
}

type APIPerformanceOperationsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceOperation *components.PublicAPIPerformanceOperation
}

func (a APIPerformanceOperationsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceOperationsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceOperationsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceOperationsUpdateResponse) GetPublicAPIPerformanceOperation() *components.PublicAPIPerformanceOperation {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceOperation
}
