// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformancePromptsUpdateRequest struct {
	PromptID string                                        `pathParam:"style=simple,explode=false,name=prompt_id"`
	Body     components.UpdatePublicOperationPromptRequest `request:"mediaType=application/json"`
}

func (a *APIPerformancePromptsUpdateRequest) GetPromptID() string {
	if a == nil {
		return ""
	}
	return a.PromptID
}

func (a *APIPerformancePromptsUpdateRequest) GetBody() components.UpdatePublicOperationPromptRequest {
	if a == nil {
		return components.UpdatePublicOperationPromptRequest{}
	}
	return a.Body
}

type APIPerformancePromptsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOperationPrompt *components.PublicOperationPrompt
}

func (a APIPerformancePromptsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformancePromptsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformancePromptsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformancePromptsUpdateResponse) GetPublicOperationPrompt() *components.PublicOperationPrompt {
	if a == nil {
		return nil
	}
	return a.PublicOperationPrompt
}
