// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceOperationPromptsCreateRequest struct {
	OperationID string                                        `pathParam:"style=simple,explode=false,name=operation_id"`
	Body        components.CreatePublicOperationPromptRequest `request:"mediaType=application/json"`
}

func (a *APIPerformanceOperationPromptsCreateRequest) GetOperationID() string {
	if a == nil {
		return ""
	}
	return a.OperationID
}

func (a *APIPerformanceOperationPromptsCreateRequest) GetBody() components.CreatePublicOperationPromptRequest {
	if a == nil {
		return components.CreatePublicOperationPromptRequest{}
	}
	return a.Body
}

type APIPerformanceOperationPromptsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOperationPrompt *components.PublicOperationPrompt
}

func (a APIPerformanceOperationPromptsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceOperationPromptsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceOperationPromptsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceOperationPromptsCreateResponse) GetPublicOperationPrompt() *components.PublicOperationPrompt {
	if a == nil {
		return nil
	}
	return a.PublicOperationPrompt
}
