// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceUseCasesRetrieveRequest struct {
	UseCaseID string `pathParam:"style=simple,explode=false,name=use_case_id"`
}

func (a *APIPerformanceUseCasesRetrieveRequest) GetUseCaseID() string {
	if a == nil {
		return ""
	}
	return a.UseCaseID
}

type APIPerformanceUseCasesRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicAPIPerformanceUseCase *components.PublicAPIPerformanceUseCase
}

func (a APIPerformanceUseCasesRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceUseCasesRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceUseCasesRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceUseCasesRetrieveResponse) GetPublicAPIPerformanceUseCase() *components.PublicAPIPerformanceUseCase {
	if a == nil {
		return nil
	}
	return a.PublicAPIPerformanceUseCase
}
