// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceEvalsListRequest struct {
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand         optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
	IntegrationID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=integration_id"`
	Enabled       optionalnullable.OptionalNullable[bool]   `queryParam:"style=form,explode=true,name=enabled"`
}

func (a *APIPerformanceEvalsListRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

func (a *APIPerformanceEvalsListRequest) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.IntegrationID
}

func (a *APIPerformanceEvalsListRequest) GetEnabled() optionalnullable.OptionalNullable[bool] {
	if a == nil {
		return nil
	}
	return a.Enabled
}

type APIPerformanceEvalsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalDefinitionsResponse *components.PublicEvalDefinitionsResponse
}

func (a APIPerformanceEvalsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceEvalsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceEvalsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceEvalsListResponse) GetPublicEvalDefinitionsResponse() *components.PublicEvalDefinitionsResponse {
	if a == nil {
		return nil
	}
	return a.PublicEvalDefinitionsResponse
}
