// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5af9b0d95688

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
	"github.com/usesapient/cli/internal/sdk/types"
)

type APIPerformanceConfigRetrieveRequest struct {
	SourceID *string `queryParam:"style=form,explode=true,name=source_id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	configScope *string `const:"custom_evals" queryParam:"style=form,explode=true,name=config_scope"`
}

func (a APIPerformanceConfigRetrieveRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigRetrieveRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigRetrieveRequest) GetSourceID() *string {
	if a == nil {
		return nil
	}
	return a.SourceID
}

func (a *APIPerformanceConfigRetrieveRequest) GetConfigScope() *string {
	return types.Pointer("custom_evals")
}

type APIPerformanceConfigRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalConfigResponse *components.PublicEvalConfigResponse
}

func (a APIPerformanceConfigRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceConfigRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceConfigRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceConfigRetrieveResponse) GetPublicEvalConfigResponse() *components.PublicEvalConfigResponse {
	if a == nil {
		return nil
	}
	return a.PublicEvalConfigResponse
}
