// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceEvalsRetrieveRequest struct {
	EvalID string `pathParam:"style=simple,explode=false,name=eval_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
}

func (a *APIPerformanceEvalsRetrieveRequest) GetEvalID() string {
	if a == nil {
		return ""
	}
	return a.EvalID
}

func (a *APIPerformanceEvalsRetrieveRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

type APIPerformanceEvalsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicEvalDefinition *components.PublicEvalDefinition
}

func (a APIPerformanceEvalsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceEvalsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceEvalsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceEvalsRetrieveResponse) GetPublicEvalDefinition() *components.PublicEvalDefinition {
	if a == nil {
		return nil
	}
	return a.PublicEvalDefinition
}
