// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceActionsVerifyRequest struct {
	ActionID string `pathParam:"style=simple,explode=false,name=action_id"`
	// Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Brand optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=brand"`
}

func (a *APIPerformanceActionsVerifyRequest) GetActionID() string {
	if a == nil {
		return ""
	}
	return a.ActionID
}

func (a *APIPerformanceActionsVerifyRequest) GetBrand() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Brand
}

type APIPerformanceActionsVerifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicVerifyActionResponse *components.PublicVerifyActionResponse
}

func (a APIPerformanceActionsVerifyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceActionsVerifyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceActionsVerifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceActionsVerifyResponse) GetPublicVerifyActionResponse() *components.PublicVerifyActionResponse {
	if a == nil {
		return nil
	}
	return a.PublicVerifyActionResponse
}
