// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd2ca97b099c

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceStarterProjectsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicStartingProject *components.PublicStartingProject
}

func (a APIPerformanceStarterProjectsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceStarterProjectsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceStarterProjectsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceStarterProjectsCreateResponse) GetPublicStartingProject() *components.PublicStartingProject {
	if a == nil {
		return nil
	}
	return a.PublicStartingProject
}
