// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceUseCasesDeleteRequest struct {
	UseCaseID string `pathParam:"style=simple,explode=false,name=use_case_id"`
}

func (a *APIPerformanceUseCasesDeleteRequest) GetUseCaseID() string {
	if a == nil {
		return ""
	}
	return a.UseCaseID
}

type APIPerformanceUseCasesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOkResponse *components.PublicOkResponse
}

func (a APIPerformanceUseCasesDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceUseCasesDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceUseCasesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceUseCasesDeleteResponse) GetPublicOkResponse() *components.PublicOkResponse {
	if a == nil {
		return nil
	}
	return a.PublicOkResponse
}
