// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type APIPerformanceUseCasesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseAPIPerformanceUseCasesList []components.PublicAPIPerformanceUseCase
}

func (a APIPerformanceUseCasesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIPerformanceUseCasesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIPerformanceUseCasesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *APIPerformanceUseCasesListResponse) GetResponseAPIPerformanceUseCasesList() []components.PublicAPIPerformanceUseCase {
	if a == nil {
		return nil
	}
	return a.ResponseAPIPerformanceUseCasesList
}
