// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsTopicsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponsePromptsTopicsList []components.PublicPromptTopic
}

func (p PromptsTopicsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsTopicsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsTopicsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsTopicsListResponse) GetResponsePromptsTopicsList() []components.PublicPromptTopic {
	if p == nil {
		return nil
	}
	return p.ResponsePromptsTopicsList
}
