// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f656f0b3199e

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsTopicsUpdateRequest struct {
	TopicID string                              `pathParam:"style=simple,explode=false,name=topic_id"`
	Body    components.UpdatePromptTopicRequest `request:"mediaType=application/json"`
}

func (p *PromptsTopicsUpdateRequest) GetTopicID() string {
	if p == nil {
		return ""
	}
	return p.TopicID
}

func (p *PromptsTopicsUpdateRequest) GetBody() components.UpdatePromptTopicRequest {
	if p == nil {
		return components.UpdatePromptTopicRequest{}
	}
	return p.Body
}

type PromptsTopicsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicPromptTopic *components.PublicPromptTopic
}

func (p PromptsTopicsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsTopicsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsTopicsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsTopicsUpdateResponse) GetPublicPromptTopic() *components.PublicPromptTopic {
	if p == nil {
		return nil
	}
	return p.PublicPromptTopic
}
