// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicPrompt *components.PublicPrompt
}

func (p PromptsCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsCreateResponse) GetPublicPrompt() *components.PublicPrompt {
	if p == nil {
		return nil
	}
	return p.PublicPrompt
}
