// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type Category string

const (
	CategoryQuickWins Category = "quick_wins"
	CategoryGrowth    Category = "growth"
	CategoryRefresh   Category = "refresh"
	CategoryCitations Category = "citations"
)

func (e Category) ToPointer() *Category {
	return &e
}
func (e *Category) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "quick_wins":
		fallthrough
	case "growth":
		fallthrough
	case "refresh":
		fallthrough
	case "citations":
		*e = Category(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Category: %v", v)
	}
}

type OpportunityType string

const (
	OpportunityTypeAlmostWinning       OpportunityType = "almost_winning"
	OpportunityTypeNegativeSentiment   OpportunityType = "negative_sentiment"
	OpportunityTypeLostWins            OpportunityType = "lost_wins"
	OpportunityTypeCompetitorGaps      OpportunityType = "competitor_gaps"
	OpportunityTypeUntappedTopics      OpportunityType = "untapped_topics"
	OpportunityTypePlatformBlindSpots  OpportunityType = "platform_blind_spots"
	OpportunityTypeContentGaps         OpportunityType = "content_gaps"
	OpportunityTypeDecliningVisibility OpportunityType = "declining_visibility"
	OpportunityTypeVolatileVisibility  OpportunityType = "volatile_visibility"
	OpportunityTypeCitationGaps        OpportunityType = "citation_gaps"
	OpportunityTypeHighCitationSources OpportunityType = "high_citation_sources"
	OpportunityTypeListicleTargets     OpportunityType = "listicle_targets"
)

func (e OpportunityType) ToPointer() *OpportunityType {
	return &e
}
func (e *OpportunityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "almost_winning":
		fallthrough
	case "negative_sentiment":
		fallthrough
	case "lost_wins":
		fallthrough
	case "competitor_gaps":
		fallthrough
	case "untapped_topics":
		fallthrough
	case "platform_blind_spots":
		fallthrough
	case "content_gaps":
		fallthrough
	case "declining_visibility":
		fallthrough
	case "volatile_visibility":
		fallthrough
	case "citation_gaps":
		fallthrough
	case "high_citation_sources":
		fallthrough
	case "listicle_targets":
		*e = OpportunityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpportunityType: %v", v)
	}
}

type PromptsActionsListRequest struct {
	Since             optionalnullable.OptionalNullable[string]          `queryParam:"style=form,explode=true,name=since"`
	StartDate         optionalnullable.OptionalNullable[string]          `queryParam:"style=form,explode=true,name=start_date"`
	EndDate           optionalnullable.OptionalNullable[string]          `queryParam:"style=form,explode=true,name=end_date"`
	Category          optionalnullable.OptionalNullable[Category]        `queryParam:"style=form,explode=true,name=category"`
	OpportunityType   optionalnullable.OptionalNullable[OpportunityType] `queryParam:"style=form,explode=true,name=opportunity_type"`
	TopicID           optionalnullable.OptionalNullable[string]          `queryParam:"style=form,explode=true,name=topic_id"`
	PromptIds         optionalnullable.OptionalNullable[string]          `queryParam:"style=form,explode=true,name=prompt_ids"`
	IncludeCitedPages *bool                                              `default:"true" queryParam:"style=form,explode=true,name=include_cited_pages"`
	Limit             *int64                                             `default:"50" queryParam:"style=form,explode=true,name=limit"`
	CitedPagesLimit   *int64                                             `default:"20" queryParam:"style=form,explode=true,name=cited_pages_limit"`
}

func (p PromptsActionsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsActionsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsActionsListRequest) GetSince() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Since
}

func (p *PromptsActionsListRequest) GetStartDate() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.StartDate
}

func (p *PromptsActionsListRequest) GetEndDate() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.EndDate
}

func (p *PromptsActionsListRequest) GetCategory() optionalnullable.OptionalNullable[Category] {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *PromptsActionsListRequest) GetOpportunityType() optionalnullable.OptionalNullable[OpportunityType] {
	if p == nil {
		return nil
	}
	return p.OpportunityType
}

func (p *PromptsActionsListRequest) GetTopicID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.TopicID
}

func (p *PromptsActionsListRequest) GetPromptIds() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.PromptIds
}

func (p *PromptsActionsListRequest) GetIncludeCitedPages() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeCitedPages
}

func (p *PromptsActionsListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PromptsActionsListRequest) GetCitedPagesLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.CitedPagesLimit
}

type PromptsActionsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PromptActionablesResponse *components.PromptActionablesResponse
}

func (p PromptsActionsListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsActionsListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsActionsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsActionsListResponse) GetPromptActionablesResponse() *components.PromptActionablesResponse {
	if p == nil {
		return nil
	}
	return p.PromptActionablesResponse
}
