// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4920048e52c0

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsUpdateRequest struct {
	PromptID string                               `pathParam:"style=simple,explode=false,name=prompt_id"`
	Body     components.UpdatePublicPromptRequest `request:"mediaType=application/json"`
}

func (p *PromptsUpdateRequest) GetPromptID() string {
	if p == nil {
		return ""
	}
	return p.PromptID
}

func (p *PromptsUpdateRequest) GetBody() components.UpdatePublicPromptRequest {
	if p == nil {
		return components.UpdatePublicPromptRequest{}
	}
	return p.Body
}

type PromptsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicPrompt *components.PublicPrompt
}

func (p PromptsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsUpdateResponse) GetPublicPrompt() *components.PublicPrompt {
	if p == nil {
		return nil
	}
	return p.PublicPrompt
}
