// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: eae02c9316db

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsRetrieveRequest struct {
	PromptID string `pathParam:"style=simple,explode=false,name=prompt_id"`
}

func (p *PromptsRetrieveRequest) GetPromptID() string {
	if p == nil {
		return ""
	}
	return p.PromptID
}

type PromptsRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicPrompt *components.PublicPrompt
}

func (p PromptsRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsRetrieveResponse) GetPublicPrompt() *components.PublicPrompt {
	if p == nil {
		return nil
	}
	return p.PublicPrompt
}
