// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PromptsTopicsDeleteRequest struct {
	TopicID        string `pathParam:"style=simple,explode=false,name=topic_id"`
	ArchivePrompts *bool  `default:"false" queryParam:"style=form,explode=true,name=archive_prompts"`
}

func (p PromptsTopicsDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsTopicsDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsTopicsDeleteRequest) GetTopicID() string {
	if p == nil {
		return ""
	}
	return p.TopicID
}

func (p *PromptsTopicsDeleteRequest) GetArchivePrompts() *bool {
	if p == nil {
		return nil
	}
	return p.ArchivePrompts
}

type PromptsTopicsDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PublicOkResponse *components.PublicOkResponse
}

func (p PromptsTopicsDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptsTopicsDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptsTopicsDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PromptsTopicsDeleteResponse) GetPublicOkResponse() *components.PublicOkResponse {
	if p == nil {
		return nil
	}
	return p.PublicOkResponse
}
