// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3ad6eee62ce1

package sdkerrors

import (
	"encoding/json"
	"github.com/usesapient/cli/internal/sdk/models/components"
)

// APIPerformanceCustomEvalsHistoryListNotFoundError - The organization does not have a configured API Performance scope.
type APIPerformanceCustomEvalsHistoryListNotFoundError struct {
	Detail   string                  `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &APIPerformanceCustomEvalsHistoryListNotFoundError{}

func (e *APIPerformanceCustomEvalsHistoryListNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
