// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: db8efaf83683

package sdkerrors

import (
	"encoding/json"
	"github.com/usesapient/cli/internal/sdk/models/components"
)

// EvalRunsRetrieveNotFoundError - The eval run does not exist or is not visible to this API key.
type EvalRunsRetrieveNotFoundError struct {
	Detail   string                  `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &EvalRunsRetrieveNotFoundError{}

func (e *EvalRunsRetrieveNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
