// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package status

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

// initAuthStatusGetCmd initializes the auth-status-get command.
func initAuthStatusGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "auth-status-get",
		Short:   "Get Auth Status",
		Long:    "Get Auth Status",
		Example: "  sapient status auth-status-get",
		RunE:    runAuthStatusGetCmd,
		Aliases: []string{"asg"},
	}
	parent.AddCommand(cmd)
	return nil
}

// runAuthStatusGetCmd executes the auth-status-get command.
func runAuthStatusGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Status.AuthStatusGet(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
