// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ca67a2312595

package evalruns

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var evalRunsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "eval-run-id", Shorthand: "e", FieldPath: "EvalRunID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initEvalRunsRetrieveCmd initializes the eval-runs-retrieve command.
func initEvalRunsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve",
		Short:   "Retrieve Eval Run",
		Long:    "Retrieve status and progress for a durable eval run.\n\nThe `eval_run_id` is the `id` returned by `POST /v1/eval-runs`. Progress is\ncomputed from the parent job, its dispatch, and child jobs when dispatch\nfanout has started.",
		Example: "  sapient eval-runs retrieve --eval-run-id <id>",
		RunE:    runEvalRunsRetrieveCmd,
	}
	flagutil.RegisterFlags(cmd, evalRunsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.EvalRunsRetrieveRequest](evalRunsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for eval-runs-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runEvalRunsRetrieveCmd executes the eval-runs-retrieve command.
func runEvalRunsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, evalRunsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, evalRunsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.EvalRunsRetrieveRequest](cmd, evalRunsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.EvalRuns.EvalRunsRetrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
