// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a77f3446358b

package evalruns

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

// initEvalRunsCreateCmd initializes the eval-runs-create command.
func initEvalRunsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create Eval Run",
		Long:    "Start a durable eval run and return the parent job ID to poll.\n\nFor prompt evals, provide explicit `targets` to override the configured\nprompt targets, or omit `targets` to use the organization's configured\nscheduled prompt targets. For API Performance evals, explicit `targets` or\n`models` override the stored configuration; when omitted, Sapient uses\nconfigured scheduled targets or legacy configured models. Custom eval runs\nuse `custom_eval_ids` when provided, otherwise the configured custom eval\nset for the organization.\n\nEvery run is queued through the durable job queue. The response `id` is the\n`eval_run_id` to pass to `GET /v1/eval-runs/{eval_run_id}`.",
		Example: "  sapient eval-runs create --request '{\"type\":\"api_performance\",\"source_type\":\"cli\"}'",
		RunE:    runEvalRunsCreateCmd,
	}
	cmd.Flags().String("request", "", "Request body as JSON [required]. Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runEvalRunsCreateCmd executes the eval-runs-create command.
func runEvalRunsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPromptForBody(cmd, "request") {
		if err := interactive.PromptForBodyJSON(cmd, "request", "Request body as JSON [required]. Can also be provided via stdin."); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequestBody[operations.EvalRunsCreateRequest](cmd, "request", `request:"mediaType=application/json"`, true)
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.EvalRuns.EvalRunsCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
