// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6b9d97c04d7b

package main

import (
	"fmt"
	"os"

	"github.com/usesapient/cli/internal/cli"
)

// version and buildTime can be set at build time using Go linker flags:
//
//	go build -ldflags "-X main.version=x.y.z -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" ./cmd/sapient
var version string
var buildTime string

func main() {
	if version != "" {
		cli.Version = version
	}
	if buildTime != "" {
		cli.BuildTime = buildTime
	}

	if err := cli.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
