// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 82b17f84f279

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceSkillsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "brand", Shorthand: "b", FieldPath: "Brand", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=brand"`, Description: "Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand."},
	{FlagName: "integration-id", Shorthand: "i", FieldPath: "IntegrationID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=integration_id"`, Description: "string value"},
	{FlagName: "source-id", FieldPath: "SourceID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=source_id"`, Description: "string value"},
	{FlagName: "enabled", Shorthand: "e", FieldPath: "Enabled", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=enabled"`, Description: "boolean flag"},
	{FlagName: "stale", FieldPath: "Stale", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=stale"`, Description: "boolean flag"},
}

// initApiPerformanceSkillsListCmd initializes the api-performance-skills-list command.
func initApiPerformanceSkillsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "skills-list",
		Short:   "List Skills",
		Long:    "List Skills",
		Example: "  sapient api-performance skills-list",
		RunE:    runApiPerformanceSkillsListCmd,
		Aliases: []string{"sl"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceSkillsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceSkillsListRequest](apiPerformanceSkillsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-skills-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceSkillsListCmd executes the api-performance-skills-list command.
func runApiPerformanceSkillsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceSkillsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceSkillsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceSkillsListRequest](cmd, apiPerformanceSkillsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceSkillsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
