// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e6b84c97ed38

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceCustomEvalsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt", FieldPath: "Prompt", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "prompt-template", FieldPath: "PromptTemplate", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional template used to render prompt before storing. Available variables: Company name { {company_name} }; Company domain { {company_domain} }."},
	{FlagName: "category-name", FieldPath: "CategoryName", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "competitor", FieldPath: "Competitor", Kind: flagutil.FlagKindString, Optional: true, Description: "Competitor ID to render this custom eval against."},
	{FlagName: "prompt-competitor-group", FieldPath: "PromptCompetitorGroup", Kind: flagutil.FlagKindString, Optional: true, Description: "Base custom eval ID that this competitor variant belongs to."},
	{FlagName: "eval", Shorthand: "e", FieldPath: "Eval", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"eval,omitempty"`, Description: "JSON object"},
}

// initApiPerformanceCustomEvalsCreateCmd initializes the api-performance-custom-evals-create command.
func initApiPerformanceCustomEvalsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "custom-evals-create",
		Short:   "Create Custom Eval",
		Long:    "Create Custom Eval",
		Example: "  sapient api-performance custom-evals-create --prompt <value>",
		RunE:    runApiPerformanceCustomEvalsCreateCmd,
		Aliases: []string{"cec"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceCustomEvalsCreateCmdMeta)
	if err := flagutil.ValidateMeta[components.PublicCustomEvalRequest](apiPerformanceCustomEvalsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-custom-evals-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceCustomEvalsCreateCmd executes the api-performance-custom-evals-create command.
func runApiPerformanceCustomEvalsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceCustomEvalsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceCustomEvalsCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.PublicCustomEvalRequest](cmd, apiPerformanceCustomEvalsCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceCustomEvalsCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
