// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ede62ba4979f

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceStarterProjectsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "integration-id", Shorthand: "i", FieldPath: "IntegrationID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initApiPerformanceStarterProjectsListCmd initializes the api-performance-starter-projects-list command.
func initApiPerformanceStarterProjectsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "starter-projects-list",
		Short:   "List Starter Projects",
		Long:    "List Starter Projects",
		Example: "  sapient api-performance starter-projects-list",
		RunE:    runApiPerformanceStarterProjectsListCmd,
		Aliases: []string{"spl"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceStarterProjectsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceStarterProjectsListRequest](apiPerformanceStarterProjectsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-starter-projects-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceStarterProjectsListCmd executes the api-performance-starter-projects-list command.
func runApiPerformanceStarterProjectsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceStarterProjectsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceStarterProjectsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceStarterProjectsListRequest](cmd, apiPerformanceStarterProjectsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceStarterProjectsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
