// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceEvaluationConfigRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "interface-id", Shorthand: "i", FieldPath: "InterfaceID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=interface_id"`, Description: "string value"},
}

// initApiPerformanceEvaluationConfigRetrieveCmd initializes the api-performance-evaluation-config-retrieve command.
func initApiPerformanceEvaluationConfigRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "evaluation-config-retrieve",
		Short:   "Retrieve Evaluation Config",
		Long:    "Retrieve Evaluation Config",
		Example: "  sapient api-performance evaluation-config-retrieve",
		RunE:    runApiPerformanceEvaluationConfigRetrieveCmd,
		Aliases: []string{"ecr"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceEvaluationConfigRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceEvaluationConfigRetrieveRequest](apiPerformanceEvaluationConfigRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-evaluation-config-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceEvaluationConfigRetrieveCmd executes the api-performance-evaluation-config-retrieve command.
func runApiPerformanceEvaluationConfigRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceEvaluationConfigRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceEvaluationConfigRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceEvaluationConfigRetrieveRequest](cmd, apiPerformanceEvaluationConfigRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceEvaluationConfigRetrieve(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
