// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceOperationPromptsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "operation-id", FieldPath: "OperationID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiPerformanceOperationPromptsListCmd initializes the api-performance-operation-prompts-list command.
func initApiPerformanceOperationPromptsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "operation-prompts-list",
		Short:   "List Operation Prompts",
		Long:    "List Operation Prompts",
		Example: "  sapient api-performance operation-prompts-list --operation-id <id>",
		RunE:    runApiPerformanceOperationPromptsListCmd,
		Aliases: []string{"opl"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceOperationPromptsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceOperationPromptsListRequest](apiPerformanceOperationPromptsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-operation-prompts-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceOperationPromptsListCmd executes the api-performance-operation-prompts-list command.
func runApiPerformanceOperationPromptsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceOperationPromptsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceOperationPromptsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceOperationPromptsListRequest](cmd, apiPerformanceOperationPromptsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceOperationPromptsList(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
