// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 247958547369

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceStarterProjectsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "starter-project-id", FieldPath: "StarterProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "repo-url", FieldPath: "Body.RepoURL", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "ref", FieldPath: "Body.Ref", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "subdir", FieldPath: "Body.Subdir", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "install-steps", FieldPath: "Body.InstallSteps", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"install_steps,omitempty"`, Description: "list of values"},
	{FlagName: "integration-id", FieldPath: "Body.IntegrationID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "framework", Shorthand: "f", FieldPath: "Body.Framework", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"fastify", "nuxt", "express", "spa-js", "angular", "react", "fastapi", "vite", "nextjs", "custom"}, Description: "options: fastify, nuxt, express, spa-js, angular, react, fastapi, vite, nextjs, custom"},
	{FlagName: "enabled", Shorthand: "e", FieldPath: "Body.Enabled", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initApiPerformanceStarterProjectsUpdateCmd initializes the api-performance-starter-projects-update command.
func initApiPerformanceStarterProjectsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "starter-projects-update",
		Short:   "Update Starter Project",
		Long:    "Update Starter Project",
		Example: "  sapient api-performance starter-projects-update --starter-project-id <id>",
		RunE:    runApiPerformanceStarterProjectsUpdateCmd,
		Aliases: []string{"spu"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceStarterProjectsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceStarterProjectsUpdateRequest](apiPerformanceStarterProjectsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-starter-projects-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceStarterProjectsUpdateCmd executes the api-performance-starter-projects-update command.
func runApiPerformanceStarterProjectsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceStarterProjectsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceStarterProjectsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceStarterProjectsUpdateRequest](cmd, apiPerformanceStarterProjectsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceStarterProjectsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
