// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 22a6302c003e

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceCustomEvalsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "custom-eval-id", Shorthand: "c", FieldPath: "CustomEvalID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiPerformanceCustomEvalsRetrieveCmd initializes the api-performance-custom-evals-retrieve command.
func initApiPerformanceCustomEvalsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "custom-evals-retrieve",
		Short:   "Retrieve Custom Eval",
		Long:    "Retrieve Custom Eval",
		Example: "  sapient api-performance custom-evals-retrieve --custom-eval-id <id>",
		RunE:    runApiPerformanceCustomEvalsRetrieveCmd,
		Aliases: []string{"cer"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceCustomEvalsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceCustomEvalsRetrieveRequest](apiPerformanceCustomEvalsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-custom-evals-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceCustomEvalsRetrieveCmd executes the api-performance-custom-evals-retrieve command.
func runApiPerformanceCustomEvalsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceCustomEvalsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceCustomEvalsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceCustomEvalsRetrieveRequest](cmd, apiPerformanceCustomEvalsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceCustomEvalsRetrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
