// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d5ec214ea332

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceActionsVerifyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "action-id", Shorthand: "a", FieldPath: "ActionID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiPerformanceActionsVerifyCmd initializes the api-performance-actions-verify command.
func initApiPerformanceActionsVerifyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "actions-verify",
		Short:   "Verify Action",
		Long:    "Verify Action",
		Example: "  sapient api-performance actions-verify --action-id <id>",
		RunE:    runApiPerformanceActionsVerifyCmd,
		Aliases: []string{"av"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceActionsVerifyCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceActionsVerifyRequest](apiPerformanceActionsVerifyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-actions-verify: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceActionsVerifyCmd executes the api-performance-actions-verify command.
func runApiPerformanceActionsVerifyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceActionsVerifyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceActionsVerifyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceActionsVerifyRequest](cmd, apiPerformanceActionsVerifyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceActionsVerify(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
