// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceActionsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "action-id", Shorthand: "a", FieldPath: "ActionID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "brand", Shorthand: "b", FieldPath: "Brand", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=brand"`, Description: "Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand."},
	{FlagName: "include-prompt", Shorthand: "i", FieldPath: "IncludePrompt", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
}

// initApiPerformanceActionsRetrieveCmd initializes the api-performance-actions-retrieve command.
func initApiPerformanceActionsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "actions-retrieve",
		Short:   "Retrieve Action",
		Long:    "Retrieve Action",
		Example: "  sapient api-performance actions-retrieve --action-id <id>",
		RunE:    runApiPerformanceActionsRetrieveCmd,
		Aliases: []string{"are"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceActionsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceActionsRetrieveRequest](apiPerformanceActionsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-actions-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceActionsRetrieveCmd executes the api-performance-actions-retrieve command.
func runApiPerformanceActionsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceActionsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceActionsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceActionsRetrieveRequest](cmd, apiPerformanceActionsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceActionsRetrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
