// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceOperationPromptsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "operation-id", FieldPath: "OperationID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "prompt", Shorthand: "p", FieldPath: "Body.Prompt", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "eval-type", FieldPath: "Body.EvalType", Kind: flagutil.FlagKindString, Optional: true, HasDefault: true, DefaultStr: "integration", Description: "string value"},
	{FlagName: "expected-behavior", FieldPath: "Body.ExpectedBehavior", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"expected_behavior,omitempty"`, Description: "string value"},
	{FlagName: "graders", Shorthand: "g", FieldPath: "Body.Graders", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"graders,omitempty"`, Description: "list of values"},
	{FlagName: "reference-answer", Shorthand: "r", FieldPath: "Body.ReferenceAnswer", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"reference_answer,omitempty"`, Description: "string value"},
}

// initApiPerformanceOperationPromptsCreateCmd initializes the api-performance-operation-prompts-create command.
func initApiPerformanceOperationPromptsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "operation-prompts-create",
		Short:   "Create Operation Prompt",
		Long:    "Create Operation Prompt",
		Example: "  sapient api-performance operation-prompts-create --operation-id <id> --prompt <value>",
		RunE:    runApiPerformanceOperationPromptsCreateCmd,
		Aliases: []string{"opc"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceOperationPromptsCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceOperationPromptsCreateRequest](apiPerformanceOperationPromptsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-operation-prompts-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceOperationPromptsCreateCmd executes the api-performance-operation-prompts-create command.
func runApiPerformanceOperationPromptsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceOperationPromptsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceOperationPromptsCreateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceOperationPromptsCreateRequest](cmd, apiPerformanceOperationPromptsCreateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceOperationPromptsCreate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
