// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 27710f4dde8c

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceConfigRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "source-id", Shorthand: "s", FieldPath: "SourceID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initApiPerformanceConfigRetrieveCmd initializes the api-performance-config-retrieve command.
func initApiPerformanceConfigRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "config-retrieve",
		Short:   "Retrieve Eval Config",
		Long:    "Retrieve Eval Config",
		Example: "  sapient api-performance config-retrieve",
		RunE:    runApiPerformanceConfigRetrieveCmd,
		Aliases: []string{"cr"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceConfigRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceConfigRetrieveRequest](apiPerformanceConfigRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-config-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceConfigRetrieveCmd executes the api-performance-config-retrieve command.
func runApiPerformanceConfigRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceConfigRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceConfigRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceConfigRetrieveRequest](cmd, apiPerformanceConfigRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceConfigRetrieve(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
