// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceConfigUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "brand", Shorthand: "b", FieldPath: "Brand", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=brand"`, Description: "Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand."},
	{FlagName: "models", Shorthand: "m", FieldPath: "Body.Models", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"models,omitempty"`, Description: "Legacy flat model selection. Prefer targets for v0.3.0."},
	{FlagName: "targets", Shorthand: "t", FieldPath: "Body.Targets", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"targets,omitempty"`, Description: "Scheduled text/agent targets. Use frequency='manual' to keep a target available but unscheduled."},
	{FlagName: "endpoint-ids", FieldPath: "Body.EndpointIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"endpoint_ids,omitempty"`, Description: "list of values"},
	{FlagName: "custom-eval-ids", Shorthand: "c", FieldPath: "Body.CustomEvalIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"custom_eval_ids,omitempty"`, Description: "list of values"},
	{FlagName: "env-vars", FieldPath: "Body.EnvVars", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"env_vars,omitempty"`, Description: "value"},
	{FlagName: "env-profiles", FieldPath: "Body.EnvProfiles", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"env_profiles,omitempty"`, Description: "list of values"},
	{FlagName: "default-env-profile-id", FieldPath: "Body.DefaultEnvProfileID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"default_env_profile_id,omitempty"`, Description: "string value"},
	{FlagName: "integration-id", Shorthand: "i", FieldPath: "Body.IntegrationID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"integration_id,omitempty"`, Description: "string value"},
	{FlagName: "api-base-url", Shorthand: "a", FieldPath: "Body.APIBaseURL", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"api_base_url,omitempty"`, Description: "string value"},
}

// initApiPerformanceConfigUpdateCmd initializes the api-performance-config-update command.
func initApiPerformanceConfigUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "config-update",
		Short:   "Update Eval Config",
		Long:    "Update Eval Config",
		Example: "  sapient api-performance config-update",
		RunE:    runApiPerformanceConfigUpdateCmd,
		Aliases: []string{"cu"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceConfigUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceConfigUpdateRequest](apiPerformanceConfigUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-config-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceConfigUpdateCmd executes the api-performance-config-update command.
func runApiPerformanceConfigUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceConfigUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceConfigUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceConfigUpdateRequest](cmd, apiPerformanceConfigUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceConfigUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
