// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceOperationsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "method", Shorthand: "m", FieldPath: "Method", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "path", Shorthand: "p", FieldPath: "Path", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "string value"},
	{FlagName: "category-name", FieldPath: "CategoryName", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"category_name,omitempty"`, Description: "string value"},
	{FlagName: "category-slug", FieldPath: "CategorySlug", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"category_slug,omitempty"`, Description: "string value"},
	{FlagName: "openapi-operation-id", FieldPath: "OpenapiOperationID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"openapi_operation_id,omitempty"`, Description: "string value"},
	{FlagName: "interface-id", Shorthand: "i", FieldPath: "InterfaceID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"interface_id,omitempty"`, Description: "string value"},
}

// initApiPerformanceOperationsCreateCmd initializes the api-performance-operations-create command.
func initApiPerformanceOperationsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "operations-create",
		Short:   "Create Operation",
		Long:    "Create Operation",
		Example: "  sapient api-performance operations-create --method <value> --path /var",
		RunE:    runApiPerformanceOperationsCreateCmd,
		Aliases: []string{"oc"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceOperationsCreateCmdMeta)
	if err := flagutil.ValidateMeta[components.CreatePublicAPIPerformanceOperationRequest](apiPerformanceOperationsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-operations-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceOperationsCreateCmd executes the api-performance-operations-create command.
func runApiPerformanceOperationsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceOperationsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceOperationsCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreatePublicAPIPerformanceOperationRequest](cmd, apiPerformanceOperationsCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceOperationsCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
