// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7760166dee6d

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceEvalsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "eval-id", FieldPath: "EvalID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "custom-prompt", FieldPath: "Body.CustomPrompt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"custom_prompt,omitempty"`, Description: "string value"},
	{FlagName: "expected-behavior", FieldPath: "Body.ExpectedBehavior", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"expected_behavior,omitempty"`, Description: "string value"},
	{FlagName: "starting-project-id", FieldPath: "Body.StartingProjectID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"starting_project_id,omitempty"`, Description: "Starting project to clone before running the eval. Empty string clears it."},
	{FlagName: "docs-mode", FieldPath: "Body.DocsMode", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"docs_mode,omitempty"`, Description: "Docs behavior for this eval: default, include, or exclude. (options: default, include, exclude)"},
	{FlagName: "include-env-vars", Shorthand: "i", FieldPath: "Body.IncludeEnvVars", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"include_env_vars,omitempty"`, Description: "Include configured environment variable names in the eval prompt."},
	{FlagName: "env-profile-ids", FieldPath: "Body.EnvProfileIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"env_profile_ids,omitempty"`, Description: "Environment profile IDs to use for this eval. Empty list clears the selection."},
	{FlagName: "model-ids", FieldPath: "Body.ModelIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"model_ids,omitempty"`, Description: "Model IDs to use for this eval. Empty list uses the config-level models."},
	{FlagName: "compare-skills", FieldPath: "Body.CompareSkills", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"compare_skills,omitempty"`, Description: "boolean flag"},
	{FlagName: "skills-mode", FieldPath: "Body.SkillsMode", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"skills_mode,omitempty"`, Description: "options: none, all, selected"},
	{FlagName: "skill-ids", FieldPath: "Body.SkillIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"skill_ids,omitempty"`, Description: "Selected skill IDs. Used when skills_mode is selected."},
	{FlagName: "mcp-enabled", FieldPath: "Body.McpEnabled", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"mcp_enabled,omitempty"`, Description: "boolean flag"},
	{FlagName: "run-context", Shorthand: "r", FieldPath: "Body.RunContext", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"run_context,omitempty"`, Description: "value"},
	{FlagName: "enabled", FieldPath: "Body.Enabled", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"enabled,omitempty"`, Description: "boolean flag"},
}

// initApiPerformanceEvalsUpdateCmd initializes the api-performance-evals-update command.
func initApiPerformanceEvalsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "evals-update",
		Short:   "Update Eval Definition",
		Long:    "Update Eval Definition",
		Example: "  sapient api-performance evals-update --eval-id <id>",
		RunE:    runApiPerformanceEvalsUpdateCmd,
		Aliases: []string{"eu"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceEvalsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceEvalsUpdateRequest](apiPerformanceEvalsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-evals-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceEvalsUpdateCmd executes the api-performance-evals-update command.
func runApiPerformanceEvalsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceEvalsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceEvalsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceEvalsUpdateRequest](cmd, apiPerformanceEvalsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceEvalsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
