// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e74a92d1bb0c

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceActionsRefreshCmdMeta = []flagutil.FlagMeta{
	{FlagName: "integration-id", Shorthand: "i", FieldPath: "IntegrationID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"integration_id,omitempty"`, Description: "string value"},
	{FlagName: "force", Shorthand: "f", FieldPath: "Force", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
}

// initApiPerformanceActionsRefreshCmd initializes the api-performance-actions-refresh command.
func initApiPerformanceActionsRefreshCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "actions-refresh",
		Short:   "Refresh Actions",
		Long:    "Refresh Actions",
		Example: "  sapient api-performance actions-refresh",
		RunE:    runApiPerformanceActionsRefreshCmd,
		Aliases: []string{"ar"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceActionsRefreshCmdMeta)
	if err := flagutil.ValidateMeta[components.PublicRefreshActionsRequest](apiPerformanceActionsRefreshCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-actions-refresh: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceActionsRefreshCmd executes the api-performance-actions-refresh command.
func runApiPerformanceActionsRefreshCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceActionsRefreshCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceActionsRefreshCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.PublicRefreshActionsRequest](cmd, apiPerformanceActionsRefreshCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceActionsRefresh(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
