// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: db642485fd59

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceStarterProjectsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "starter-project-id", Shorthand: "s", FieldPath: "StarterProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "brand", Shorthand: "b", FieldPath: "Brand", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=brand"`, Description: "Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand."},
}

// initApiPerformanceStarterProjectsDeleteCmd initializes the api-performance-starter-projects-delete command.
func initApiPerformanceStarterProjectsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "starter-projects-delete",
		Short:   "Delete Starter Project",
		Long:    "Delete Starter Project",
		Example: "  sapient api-performance starter-projects-delete --starter-project-id <id>",
		RunE:    runApiPerformanceStarterProjectsDeleteCmd,
		Aliases: []string{"spd"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceStarterProjectsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceStarterProjectsDeleteRequest](apiPerformanceStarterProjectsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-starter-projects-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceStarterProjectsDeleteCmd executes the api-performance-starter-projects-delete command.
func runApiPerformanceStarterProjectsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceStarterProjectsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceStarterProjectsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceStarterProjectsDeleteRequest](cmd, apiPerformanceStarterProjectsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceStarterProjectsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
