// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceResultsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "brand", Shorthand: "b", FieldPath: "Brand", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=brand"`, Description: "Optional brand name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand."},
	{FlagName: "integration-id", FieldPath: "IntegrationID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=integration_id"`, Description: "string value"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 20, Description: "integer value"},
	{FlagName: "include-docs-audit", FieldPath: "IncludeDocsAudit", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
	{FlagName: "docs-audit-limit", FieldPath: "DocsAuditLimit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 500, Description: "integer value"},
}

// initApiPerformanceResultsRetrieveCmd initializes the api-performance-results-retrieve command.
func initApiPerformanceResultsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "results-retrieve",
		Short:   "Retrieve Results",
		Long:    "Retrieve Results",
		Example: "  sapient api-performance results-retrieve",
		RunE:    runApiPerformanceResultsRetrieveCmd,
		Aliases: []string{"rr"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceResultsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceResultsRetrieveRequest](apiPerformanceResultsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-results-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceResultsRetrieveCmd executes the api-performance-results-retrieve command.
func runApiPerformanceResultsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceResultsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceResultsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceResultsRetrieveRequest](cmd, apiPerformanceResultsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceResultsRetrieve(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
