// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7885e4048435

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceCustomEvalsHistoryListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "custom-eval-id", FieldPath: "CustomEvalID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=custom_eval_id"`, Description: "Optional custom eval ID to filter history rows."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 25, Description: "integer value"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "integer value"},
	{FlagName: "search", FieldPath: "Search", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=search"`, Description: "string value"},
	{FlagName: "result-filter", Shorthand: "r", FieldPath: "ResultFilter", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "all", EnumValues: []string{"all", "passed", "failed"}, Description: "options: all, passed, failed"},
	{FlagName: "target-key", Shorthand: "t", FieldPath: "TargetKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=target_key"`, Description: "string value"},
	{FlagName: "category-id", FieldPath: "CategoryID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=category_id"`, Description: "string value"},
	{FlagName: "sort-by", FieldPath: "SortBy", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "time", EnumValues: []string{"time", "use_case", "target", "result", "score", "tool_calls", "latency"}, Description: "options: time, use_case, target, result, score, tool_calls, latency"},
	{FlagName: "sort-dir", FieldPath: "SortDir", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "desc", EnumValues: []string{"asc", "desc"}, Description: "options: asc, desc"},
}

// initApiPerformanceCustomEvalsHistoryListCmd initializes the api-performance-custom-evals-history-list command.
func initApiPerformanceCustomEvalsHistoryListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "custom-evals-history-list",
		Short:   "List Custom Eval History",
		Long:    "List custom eval history rows for the organization.\n\nUse `custom_eval_id` to retrieve the evaluated run history for one custom\neval prompt. The public API hides infrastructure-error rows, matching the\nnon-admin dashboard behavior.",
		Example: "  sapient api-performance custom-evals-history-list",
		RunE:    runApiPerformanceCustomEvalsHistoryListCmd,
		Aliases: []string{"cehl"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceCustomEvalsHistoryListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceCustomEvalsHistoryListRequest](apiPerformanceCustomEvalsHistoryListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-custom-evals-history-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceCustomEvalsHistoryListCmd executes the api-performance-custom-evals-history-list command.
func runApiPerformanceCustomEvalsHistoryListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceCustomEvalsHistoryListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceCustomEvalsHistoryListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceCustomEvalsHistoryListRequest](cmd, apiPerformanceCustomEvalsHistoryListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceCustomEvalsHistoryList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
