// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 75cc9490af28

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceActionsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "source-id", FieldPath: "SourceID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "status", FieldPath: "Status", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "action-type", Shorthand: "a", FieldPath: "ActionType", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "priority", Shorthand: "p", FieldPath: "Priority", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 100, Description: "integer value"},
}

// initApiPerformanceActionsListCmd initializes the api-performance-actions-list command.
func initApiPerformanceActionsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "actions-list",
		Short:   "List Actions",
		Long:    "List Actions",
		Example: "  sapient api-performance actions-list",
		RunE:    runApiPerformanceActionsListCmd,
		Aliases: []string{"al"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceActionsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceActionsListRequest](apiPerformanceActionsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-actions-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceActionsListCmd executes the api-performance-actions-list command.
func runApiPerformanceActionsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceActionsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceActionsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceActionsListRequest](cmd, apiPerformanceActionsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceActionsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
