// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

// initApiPerformancePlatformsListCmd initializes the api-performance-platforms-list command.
func initApiPerformancePlatformsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "platforms-list",
		Short:   "List Platforms",
		Long:    "List Platforms",
		Example: "  sapient api-performance platforms-list",
		RunE:    runApiPerformancePlatformsListCmd,
		Aliases: []string{"pl"},
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformancePlatformsListCmd executes the api-performance-platforms-list command.
func runApiPerformancePlatformsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformancePlatformsList(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
