// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceUseCasesCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt", Shorthand: "p", FieldPath: "Prompt", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "category-name", Shorthand: "c", FieldPath: "CategoryName", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"category_name,omitempty"`, Description: "string value"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "string value"},
}

// initApiPerformanceUseCasesCreateCmd initializes the api-performance-use-cases-create command.
func initApiPerformanceUseCasesCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "use-cases-create",
		Short:   "Create Use Case",
		Long:    "Create Use Case",
		Example: "  sapient api-performance use-cases-create --prompt <value>",
		RunE:    runApiPerformanceUseCasesCreateCmd,
		Aliases: []string{"ucc"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceUseCasesCreateCmdMeta)
	if err := flagutil.ValidateMeta[components.CreatePublicAPIPerformanceUseCaseRequest](apiPerformanceUseCasesCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-use-cases-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceUseCasesCreateCmd executes the api-performance-use-cases-create command.
func runApiPerformanceUseCasesCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceUseCasesCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceUseCasesCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreatePublicAPIPerformanceUseCaseRequest](cmd, apiPerformanceUseCasesCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceUseCasesCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
