// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformancePromptsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt-id", Shorthand: "p", FieldPath: "PromptID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiPerformancePromptsDeleteCmd initializes the api-performance-prompts-delete command.
func initApiPerformancePromptsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "prompts-delete",
		Short:   "Delete Operation Prompt",
		Long:    "Delete Operation Prompt",
		Example: "  sapient api-performance prompts-delete --prompt-id <id>",
		RunE:    runApiPerformancePromptsDeleteCmd,
		Aliases: []string{"pd"},
	}
	flagutil.RegisterFlags(cmd, apiPerformancePromptsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformancePromptsDeleteRequest](apiPerformancePromptsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-prompts-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformancePromptsDeleteCmd executes the api-performance-prompts-delete command.
func runApiPerformancePromptsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformancePromptsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformancePromptsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformancePromptsDeleteRequest](cmd, apiPerformancePromptsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformancePromptsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
