// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceRunsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "run-id", Shorthand: "r", FieldPath: "RunID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApiPerformanceRunsRetrieveCmd initializes the api-performance-runs-retrieve command.
func initApiPerformanceRunsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "runs-retrieve",
		Short:   "Retrieve Eval Run",
		Long:    "Retrieve Eval Run",
		Example: "  sapient api-performance runs-retrieve --run-id <id>",
		RunE:    runApiPerformanceRunsRetrieveCmd,
		Aliases: []string{"rr"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceRunsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceRunsRetrieveRequest](apiPerformanceRunsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-runs-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceRunsRetrieveCmd executes the api-performance-runs-retrieve command.
func runApiPerformanceRunsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceRunsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceRunsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceRunsRetrieveRequest](cmd, apiPerformanceRunsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceRunsRetrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
