// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3ff06ac6da8b

package apiperformance

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var apiPerformanceSourcesListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "include-system", Shorthand: "i", FieldPath: "IncludeSystem", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
}

// initApiPerformanceSourcesListCmd initializes the api-performance-sources-list command.
func initApiPerformanceSourcesListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "sources-list",
		Short:   "List Sources",
		Long:    "List Sources",
		Example: "  sapient api-performance sources-list",
		RunE:    runApiPerformanceSourcesListCmd,
		Aliases: []string{"sli"},
	}
	flagutil.RegisterFlags(cmd, apiPerformanceSourcesListCmdMeta)
	if err := flagutil.ValidateMeta[operations.APIPerformanceSourcesListRequest](apiPerformanceSourcesListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for api-performance-sources-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApiPerformanceSourcesListCmd executes the api-performance-sources-list command.
func runApiPerformanceSourcesListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, apiPerformanceSourcesListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, apiPerformanceSourcesListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.APIPerformanceSourcesListRequest](cmd, apiPerformanceSourcesListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIPerformance.APIPerformanceSourcesList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
