// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiperformance

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/usage"
)

func InitApiPerformanceRoot(parent *cobra.Command) error {
	var ApiPerformanceCmd = &cobra.Command{
		Use:   "api-performance",
		Short: "Operations for api-performance",
		Long:  "Operations for api-performance",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ap"},
	}

	if err := initApiPerformancePlatformsListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformancePlatformsEstimateCostCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceInterfacesListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceEvaluationConfigRetrieveCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceEvaluationConfigUpdateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationsListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationsCreateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationsRetrieveCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationsUpdateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationsDeleteCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationPromptsListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceOperationPromptsCreateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceRunsListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceRunsRetrieveCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformancePromptsRetrieveCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformancePromptsUpdateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformancePromptsDeleteCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceUseCasesListCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceUseCasesCreateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceUseCasesRetrieveCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceUseCasesUpdateCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	if err := initApiPerformanceUseCasesDeleteCmd(ApiPerformanceCmd); err != nil {
		return err
	}

	parent.AddCommand(ApiPerformanceCmd)
	return nil
}
