// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 46e531e327b7

package prompts

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

// initPromptsConfigRetrieveCmd initializes the prompts-config-retrieve command.
func initPromptsConfigRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "config-retrieve",
		Short:   "Retrieve Prompt Config",
		Long:    "Retrieve Prompt Config",
		Example: "  sapient prompts config-retrieve",
		RunE:    runPromptsConfigRetrieveCmd,
		Aliases: []string{"cr"},
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsConfigRetrieveCmd executes the prompts-config-retrieve command.
func runPromptsConfigRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsConfigRetrieve(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
