// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0bd9664ed011

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "topic-id", Shorthand: "t", FieldPath: "TopicID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "is-active", FieldPath: "IsActive", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "status", Shorthand: "s", FieldPath: "Status", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "include-archived", FieldPath: "IncludeArchived", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
}

// initPromptsListCmd initializes the prompts-list command.
func initPromptsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Prompts",
		Long:    "List Prompts",
		Example: "  sapient prompts list",
		RunE:    runPromptsListCmd,
	}
	flagutil.RegisterFlags(cmd, promptsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsListRequest](promptsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsListCmd executes the prompts-list command.
func runPromptsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsListRequest](cmd, promptsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
