// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsActionsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "since", FieldPath: "Since", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=since"`, Description: "string value"},
	{FlagName: "start-date", FieldPath: "StartDate", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=start_date"`, Description: "string value"},
	{FlagName: "end-date", Shorthand: "e", FieldPath: "EndDate", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=end_date"`, Description: "string value"},
	{FlagName: "tag", FieldPath: "Tag", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "all", EnumValues: []string{"cited_pages", "opportunities", "all"}, Description: "options: cited_pages, opportunities, all"},
	{FlagName: "category", FieldPath: "Category", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=category"`, Description: "options: quick_wins, growth, refresh, citations"},
	{FlagName: "opportunity-type", FieldPath: "OpportunityType", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=opportunity_type"`, Description: "options: almost_winning, negative_sentiment, lost_wins, competitor_gaps, untapped_topics, platform_blind_spots, content_gaps, declining_visibility, volatile_visibility, citation_gaps, high_citation_sources, listicle_targets"},
	{FlagName: "topic-id", FieldPath: "TopicID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=topic_id"`, Description: "string value"},
	{FlagName: "prompt-ids", Shorthand: "p", FieldPath: "PromptIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=prompt_ids"`, Description: "string value"},
	{FlagName: "include-cited-pages", Shorthand: "i", FieldPath: "IncludeCitedPages", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, DefaultBool: true, Description: "boolean flag"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "integer value"},
	{FlagName: "cited-pages-limit", FieldPath: "CitedPagesLimit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 20, Description: "integer value"},
}

// initPromptsActionsListCmd initializes the prompts-actions-list command.
func initPromptsActionsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "actions-list",
		Short:   "List Prompt Actionables",
		Long:    "List Prompt Actionables",
		Example: "  sapient prompts actions-list",
		RunE:    runPromptsActionsListCmd,
		Aliases: []string{"al"},
	}
	flagutil.RegisterFlags(cmd, promptsActionsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsActionsListRequest](promptsActionsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-actions-list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsActionsListCmd executes the prompts-actions-list command.
func runPromptsActionsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsActionsListCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsActionsListCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsActionsListRequest](cmd, promptsActionsListCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsActionsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
