// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a880a7cc4fce

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt-id", Shorthand: "p", FieldPath: "PromptID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPromptsDeleteCmd initializes the prompts-delete command.
func initPromptsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Prompt",
		Long:    "Delete Prompt",
		Example: "  sapient prompts delete --prompt-id <id>",
		RunE:    runPromptsDeleteCmd,
	}
	flagutil.RegisterFlags(cmd, promptsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsDeleteRequest](promptsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsDeleteCmd executes the prompts-delete command.
func runPromptsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsDeleteRequest](cmd, promptsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
