// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsTopicsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "topic-id", Shorthand: "t", FieldPath: "TopicID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPromptsTopicsUpdateCmd initializes the prompts-topics-update command.
func initPromptsTopicsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "topics-update",
		Short:   "Update Topic",
		Long:    "Update Topic",
		Example: "  sapient prompts topics-update --topic-id <id> --name <value>",
		RunE:    runPromptsTopicsUpdateCmd,
		Aliases: []string{"tu"},
	}
	flagutil.RegisterFlags(cmd, promptsTopicsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsTopicsUpdateRequest](promptsTopicsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-topics-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPromptsTopicsUpdateCmd executes the prompts-topics-update command.
func runPromptsTopicsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsTopicsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsTopicsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsTopicsUpdateRequest](cmd, promptsTopicsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsTopicsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
