// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e6688257e5c4

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsUpdateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt-id", FieldPath: "PromptID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "text", FieldPath: "Body.Text", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"text,omitempty"`, Description: "string value"},
	{FlagName: "topic-id", FieldPath: "Body.TopicID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"topic_id,omitempty"`, Description: "string value"},
	{FlagName: "platform-ids", FieldPath: "Body.PlatformIds", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"platform_ids,omitempty"`, Description: "list of values"},
	{FlagName: "is-active", Shorthand: "i", FieldPath: "Body.IsActive", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"is_active,omitempty"`, Description: "boolean flag"},
}

// initPromptsUpdateCmd initializes the prompts-update command.
func initPromptsUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update Prompt",
		Long:    "Update Prompt",
		Example: "  sapient prompts update --prompt-id <id>",
		RunE:    runPromptsUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, promptsUpdateCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsUpdateRequest](promptsUpdateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPromptsUpdateCmd executes the prompts-update command.
func runPromptsUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsUpdateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsUpdateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsUpdateRequest](cmd, promptsUpdateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsUpdate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
