// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/components"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "topic-id", FieldPath: "TopicID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "text", FieldPath: "Text", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "platform-ids", Shorthand: "p", FieldPath: "PlatformIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
}

// initPromptsCreateCmd initializes the prompts-create command.
func initPromptsCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create Prompt",
		Long:    "Create Prompt",
		Example: "  sapient prompts create --topic-id <id> --text <value>",
		RunE:    runPromptsCreateCmd,
	}
	flagutil.RegisterFlags(cmd, promptsCreateCmdMeta)
	if err := flagutil.ValidateMeta[components.CreatePublicPromptRequest](promptsCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPromptsCreateCmd executes the prompts-create command.
func runPromptsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreatePublicPromptRequest](cmd, promptsCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
