// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsTopicsDeleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "topic-id", Shorthand: "t", FieldPath: "TopicID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "archive-prompts", Shorthand: "a", FieldPath: "ArchivePrompts", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "boolean flag"},
}

// initPromptsTopicsDeleteCmd initializes the prompts-topics-delete command.
func initPromptsTopicsDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "topics-delete",
		Short:   "Delete Topic",
		Long:    "Delete Topic",
		Example: "  sapient prompts topics-delete --topic-id <id>",
		RunE:    runPromptsTopicsDeleteCmd,
		Aliases: []string{"td"},
	}
	flagutil.RegisterFlags(cmd, promptsTopicsDeleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsTopicsDeleteRequest](promptsTopicsDeleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-topics-delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsTopicsDeleteCmd executes the prompts-topics-delete command.
func runPromptsTopicsDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsTopicsDeleteCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsTopicsDeleteCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsTopicsDeleteRequest](cmd, promptsTopicsDeleteCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsTopicsDelete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
