// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4ea60b3c4e14

package prompts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/client"
	"github.com/usesapient/cli/internal/flagutil"
	"github.com/usesapient/cli/internal/interactive"
	"github.com/usesapient/cli/internal/output"
	"github.com/usesapient/cli/internal/sdk"
	"github.com/usesapient/cli/internal/sdk/models/operations"
	"github.com/usesapient/cli/internal/usage"
)

var promptsRetrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt-id", Shorthand: "p", FieldPath: "PromptID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initPromptsRetrieveCmd initializes the prompts-retrieve command.
func initPromptsRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve",
		Short:   "Retrieve Prompt",
		Long:    "Retrieve Prompt",
		Example: "  sapient prompts retrieve --prompt-id <id>",
		RunE:    runPromptsRetrieveCmd,
	}
	flagutil.RegisterFlags(cmd, promptsRetrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.PromptsRetrieveRequest](promptsRetrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for prompts-retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPromptsRetrieveCmd executes the prompts-retrieve command.
func runPromptsRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, promptsRetrieveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, promptsRetrieveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PromptsRetrieveRequest](cmd, promptsRetrieveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prompts.PromptsRetrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
