// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea613f7dfa4b

package prompts

import (
	"github.com/spf13/cobra"
	"github.com/usesapient/cli/internal/usage"
)

func InitPromptsRoot(parent *cobra.Command) error {
	var PromptsCmd = &cobra.Command{
		Use:   "prompts",
		Short: "Operations for prompts",
		Long:  "Operations for prompts",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initPromptsListCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsCreateCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsConfigRetrieveCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsTopicsCreateCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsTopicsUpdateCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsTopicsDeleteCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsActionsListCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsRetrieveCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsUpdateCmd(PromptsCmd); err != nil {
		return err
	}

	if err := initPromptsDeleteCmd(PromptsCmd); err != nil {
		return err
	}

	parent.AddCommand(PromptsCmd)
	return nil
}
