// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 49de3db2f470

package components

type CreatePublicPromptsBatchRequest struct {
	Prompts []CreatePublicPromptRequest `json:"prompts"`
}

func (c *CreatePublicPromptsBatchRequest) GetPrompts() []CreatePublicPromptRequest {
	if c == nil {
		return []CreatePublicPromptRequest{}
	}
	return c.Prompts
}
