// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type CreatePublicAPIPerformanceUseCaseRequest struct {
	Prompt       string                                    `json:"prompt"`
	CategoryName optionalnullable.OptionalNullable[string] `json:"category_name,omitzero"`
	Description  optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
}

func (c *CreatePublicAPIPerformanceUseCaseRequest) GetPrompt() string {
	if c == nil {
		return ""
	}
	return c.Prompt
}

func (c *CreatePublicAPIPerformanceUseCaseRequest) GetCategoryName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.CategoryName
}

func (c *CreatePublicAPIPerformanceUseCaseRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}
