// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type CreatePublicOperationPromptRequest struct {
	Prompt           string                                    `json:"prompt"`
	EvalType         *string                                   `default:"integration" json:"eval_type"`
	ExpectedBehavior optionalnullable.OptionalNullable[string] `json:"expected_behavior,omitzero"`
	Graders          []map[string]any                          `json:"graders,omitzero"`
	ReferenceAnswer  optionalnullable.OptionalNullable[string] `json:"reference_answer,omitzero"`
}

func (c CreatePublicOperationPromptRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePublicOperationPromptRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePublicOperationPromptRequest) GetPrompt() string {
	if c == nil {
		return ""
	}
	return c.Prompt
}

func (c *CreatePublicOperationPromptRequest) GetEvalType() *string {
	if c == nil {
		return nil
	}
	return c.EvalType
}

func (c *CreatePublicOperationPromptRequest) GetExpectedBehavior() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ExpectedBehavior
}

func (c *CreatePublicOperationPromptRequest) GetGraders() []map[string]any {
	if c == nil {
		return nil
	}
	return c.Graders
}

func (c *CreatePublicOperationPromptRequest) GetReferenceAnswer() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ReferenceAnswer
}
