// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8842dce398f6

package components

type CreatePromptTopicRequest struct {
	Name string `json:"name"`
}

func (c *CreatePromptTopicRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
