// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type CreatePublicPromptRequest struct {
	TopicID     string   `json:"topic_id"`
	Text        string   `json:"text"`
	PlatformIds []string `json:"platform_ids,omitzero"`
}

func (c CreatePublicPromptRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePublicPromptRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePublicPromptRequest) GetTopicID() string {
	if c == nil {
		return ""
	}
	return c.TopicID
}

func (c *CreatePublicPromptRequest) GetText() string {
	if c == nil {
		return ""
	}
	return c.Text
}

func (c *CreatePublicPromptRequest) GetPlatformIds() []string {
	if c == nil {
		return nil
	}
	return c.PlatformIds
}
