// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b9e389f989fe

package components

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

// Format - Report format to include in the response.
type Format string

const (
	FormatJSON     Format = "json"
	FormatMarkdown Format = "markdown"
	FormatMd       Format = "md"
)

func (e Format) ToPointer() *Format {
	return &e
}
func (e *Format) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json":
		fallthrough
	case "markdown":
		fallthrough
	case "md":
		*e = Format(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Format: %v", v)
	}
}

type DiagnoseEvalRunsRequest struct {
	// Optional company name, domain, brand ID, or org brand ID. Omit when the API key resolves to one brand.
	Company optionalnullable.OptionalNullable[string] `json:"company,omitzero"`
	// Lookback window, such as 20d, 72h, or an ISO timestamp.
	Since *string `default:"20d" json:"since"`
	// Report format to include in the response.
	Format          *Format `default:"json" json:"format"`
	IncludeExamples *bool   `default:"true" json:"include_examples"`
	MaxExamples     *int64  `default:"10" json:"max_examples"`
}

func (d DiagnoseEvalRunsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiagnoseEvalRunsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DiagnoseEvalRunsRequest) GetCompany() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Company
}

func (d *DiagnoseEvalRunsRequest) GetSince() *string {
	if d == nil {
		return nil
	}
	return d.Since
}

func (d *DiagnoseEvalRunsRequest) GetFormat() *Format {
	if d == nil {
		return nil
	}
	return d.Format
}

func (d *DiagnoseEvalRunsRequest) GetIncludeExamples() *bool {
	if d == nil {
		return nil
	}
	return d.IncludeExamples
}

func (d *DiagnoseEvalRunsRequest) GetMaxExamples() *int64 {
	if d == nil {
		return nil
	}
	return d.MaxExamples
}
