// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 81c308a89605

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type DiagnosisSummary struct {
	TotalRuns          *int64                                     `default:"0" json:"total_runs"`
	FailedRuns         *int64                                     `default:"0" json:"failed_runs"`
	PassedRuns         *int64                                     `default:"0" json:"passed_runs"`
	FailureRate        optionalnullable.OptionalNullable[float64] `json:"failure_rate,omitzero"`
	TopFailedEndpoints []map[string]any                           `json:"top_failed_endpoints,omitzero"`
	TopFailedModels    []map[string]any                           `json:"top_failed_models,omitzero"`
	TopFailureReasons  []map[string]any                           `json:"top_failure_reasons,omitzero"`
}

func (d DiagnosisSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiagnosisSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DiagnosisSummary) GetTotalRuns() *int64 {
	if d == nil {
		return nil
	}
	return d.TotalRuns
}

func (d *DiagnosisSummary) GetFailedRuns() *int64 {
	if d == nil {
		return nil
	}
	return d.FailedRuns
}

func (d *DiagnosisSummary) GetPassedRuns() *int64 {
	if d == nil {
		return nil
	}
	return d.PassedRuns
}

func (d *DiagnosisSummary) GetFailureRate() optionalnullable.OptionalNullable[float64] {
	if d == nil {
		return nil
	}
	return d.FailureRate
}

func (d *DiagnosisSummary) GetTopFailedEndpoints() []map[string]any {
	if d == nil {
		return nil
	}
	return d.TopFailedEndpoints
}

func (d *DiagnosisSummary) GetTopFailedModels() []map[string]any {
	if d == nil {
		return nil
	}
	return d.TopFailedModels
}

func (d *DiagnosisSummary) GetTopFailureReasons() []map[string]any {
	if d == nil {
		return nil
	}
	return d.TopFailureReasons
}
