// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5a6617453064

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type DiagnoseEvalRunsResponse struct {
	Company         PublicCompany                             `json:"company"`
	Since           string                                    `json:"since"`
	Summary         DiagnosisSummary                          `json:"summary"`
	FailureAnalysis FailureAnalysisSnapshot                   `json:"failure_analysis"`
	Examples        []EvalRunDetail                           `json:"examples,omitzero"`
	Markdown        optionalnullable.OptionalNullable[string] `json:"markdown,omitzero"`
}

func (d DiagnoseEvalRunsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiagnoseEvalRunsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DiagnoseEvalRunsResponse) GetCompany() PublicCompany {
	if d == nil {
		return PublicCompany{}
	}
	return d.Company
}

func (d *DiagnoseEvalRunsResponse) GetSince() string {
	if d == nil {
		return ""
	}
	return d.Since
}

func (d *DiagnoseEvalRunsResponse) GetSummary() DiagnosisSummary {
	if d == nil {
		return DiagnosisSummary{}
	}
	return d.Summary
}

func (d *DiagnoseEvalRunsResponse) GetFailureAnalysis() FailureAnalysisSnapshot {
	if d == nil {
		return FailureAnalysisSnapshot{}
	}
	return d.FailureAnalysis
}

func (d *DiagnoseEvalRunsResponse) GetExamples() []EvalRunDetail {
	if d == nil {
		return nil
	}
	return d.Examples
}

func (d *DiagnoseEvalRunsResponse) GetMarkdown() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Markdown
}
