// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type EvalRunDetailEndpointType string

const (
	EvalRunDetailEndpointTypePublicEndpoint EvalRunDetailEndpointType = "PublicEndpoint"
	EvalRunDetailEndpointTypeMapOfAny       EvalRunDetailEndpointType = "mapOfAny"
	EvalRunDetailEndpointTypeUnknown        EvalRunDetailEndpointType = "Unknown"
)

type EvalRunDetailEndpoint struct {
	PublicEndpoint *PublicEndpoint `queryParam:"inline" union:"member"`
	MapOfAny       map[string]any  `queryParam:"inline" union:"member"`
	UnknownRaw     json.RawMessage `json:"-" union:"unknown"`

	Type EvalRunDetailEndpointType
}

func CreateEvalRunDetailEndpointPublicEndpoint(publicEndpoint PublicEndpoint) EvalRunDetailEndpoint {
	typ := EvalRunDetailEndpointTypePublicEndpoint

	return EvalRunDetailEndpoint{
		PublicEndpoint: &publicEndpoint,
		Type:           typ,
	}
}

func CreateEvalRunDetailEndpointMapOfAny(mapOfAny map[string]any) EvalRunDetailEndpoint {
	typ := EvalRunDetailEndpointTypeMapOfAny

	return EvalRunDetailEndpoint{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateEvalRunDetailEndpointUnknown(raw json.RawMessage) EvalRunDetailEndpoint {
	return EvalRunDetailEndpoint{
		UnknownRaw: raw,
		Type:       EvalRunDetailEndpointTypeUnknown,
	}
}

func (u EvalRunDetailEndpoint) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u EvalRunDetailEndpoint) IsUnknown() bool {
	return u.Type == EvalRunDetailEndpointTypeUnknown
}

func (u *EvalRunDetailEndpoint) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var publicEndpoint PublicEndpoint = PublicEndpoint{}
	if err := utils.UnmarshalJSON(data, &publicEndpoint, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EvalRunDetailEndpointTypePublicEndpoint,
			Value: &publicEndpoint,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EvalRunDetailEndpointTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = EvalRunDetailEndpointTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = EvalRunDetailEndpointTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EvalRunDetailEndpointType)
	switch best.Type {
	case EvalRunDetailEndpointTypePublicEndpoint:
		u.PublicEndpoint = best.Value.(*PublicEndpoint)
		return nil
	case EvalRunDetailEndpointTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = EvalRunDetailEndpointTypeUnknown
	return nil
}

func (u EvalRunDetailEndpoint) MarshalJSON() ([]byte, error) {
	if u.PublicEndpoint != nil {
		return utils.MarshalJSON(u.PublicEndpoint, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type EvalRunDetailEndpoint: all fields are null")
}

type EvalRunDetail struct {
	ID              string                                                   `json:"id"`
	Endpoint        optionalnullable.OptionalNullable[EvalRunDetailEndpoint] `json:"endpoint,omitzero"`
	Source          optionalnullable.OptionalNullable[EvalRunSource]         `json:"source,omitzero"`
	EvalType        optionalnullable.OptionalNullable[string]                `json:"eval_type,omitzero"`
	Model           optionalnullable.OptionalNullable[string]                `json:"model,omitzero"`
	ModelType       optionalnullable.OptionalNullable[string]                `json:"model_type,omitzero"`
	Platform        optionalnullable.OptionalNullable[string]                `json:"platform,omitzero"`
	Passed          optionalnullable.OptionalNullable[bool]                  `json:"passed,omitzero"`
	Score           optionalnullable.OptionalNullable[float64]               `json:"score,omitzero"`
	FailureReasons  optionalnullable.OptionalNullable[[]string]              `json:"failure_reasons,omitzero"`
	LatencyMs       optionalnullable.OptionalNullable[int64]                 `json:"latency_ms,omitzero"`
	RunAt           optionalnullable.OptionalNullable[string]                `json:"run_at,omitzero"`
	PromptSent      optionalnullable.OptionalNullable[string]                `json:"prompt_sent,omitzero"`
	ResponseText    optionalnullable.OptionalNullable[string]                `json:"response_text,omitzero"`
	ExecutionStdout optionalnullable.OptionalNullable[string]                `json:"execution_stdout,omitzero"`
	ExecutionStderr optionalnullable.OptionalNullable[string]                `json:"execution_stderr,omitzero"`
	ExitCode        optionalnullable.OptionalNullable[int64]                 `json:"exit_code,omitzero"`
	ToolCalls       optionalnullable.OptionalNullable[[]map[string]any]      `json:"tool_calls,omitzero"`
	Raw             optionalnullable.OptionalNullable[map[string]any]        `json:"raw,omitzero"`
}

func (e EvalRunDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvalRunDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvalRunDetail) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EvalRunDetail) GetEndpoint() optionalnullable.OptionalNullable[EvalRunDetailEndpoint] {
	if e == nil {
		return nil
	}
	return e.Endpoint
}

func (e *EvalRunDetail) GetSource() optionalnullable.OptionalNullable[EvalRunSource] {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *EvalRunDetail) GetEvalType() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.EvalType
}

func (e *EvalRunDetail) GetModel() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Model
}

func (e *EvalRunDetail) GetModelType() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ModelType
}

func (e *EvalRunDetail) GetPlatform() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Platform
}

func (e *EvalRunDetail) GetPassed() optionalnullable.OptionalNullable[bool] {
	if e == nil {
		return nil
	}
	return e.Passed
}

func (e *EvalRunDetail) GetScore() optionalnullable.OptionalNullable[float64] {
	if e == nil {
		return nil
	}
	return e.Score
}

func (e *EvalRunDetail) GetFailureReasons() optionalnullable.OptionalNullable[[]string] {
	if e == nil {
		return nil
	}
	return e.FailureReasons
}

func (e *EvalRunDetail) GetLatencyMs() optionalnullable.OptionalNullable[int64] {
	if e == nil {
		return nil
	}
	return e.LatencyMs
}

func (e *EvalRunDetail) GetRunAt() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.RunAt
}

func (e *EvalRunDetail) GetPromptSent() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.PromptSent
}

func (e *EvalRunDetail) GetResponseText() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ResponseText
}

func (e *EvalRunDetail) GetExecutionStdout() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ExecutionStdout
}

func (e *EvalRunDetail) GetExecutionStderr() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ExecutionStderr
}

func (e *EvalRunDetail) GetExitCode() optionalnullable.OptionalNullable[int64] {
	if e == nil {
		return nil
	}
	return e.ExitCode
}

func (e *EvalRunDetail) GetToolCalls() optionalnullable.OptionalNullable[[]map[string]any] {
	if e == nil {
		return nil
	}
	return e.ToolCalls
}

func (e *EvalRunDetail) GetRaw() optionalnullable.OptionalNullable[map[string]any] {
	if e == nil {
		return nil
	}
	return e.Raw
}
