// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type EvalRunSummaryEndpointType string

const (
	EvalRunSummaryEndpointTypePublicEndpoint EvalRunSummaryEndpointType = "PublicEndpoint"
	EvalRunSummaryEndpointTypeMapOfAny       EvalRunSummaryEndpointType = "mapOfAny"
	EvalRunSummaryEndpointTypeUnknown        EvalRunSummaryEndpointType = "Unknown"
)

type EvalRunSummaryEndpoint struct {
	PublicEndpoint *PublicEndpoint `queryParam:"inline" union:"member"`
	MapOfAny       map[string]any  `queryParam:"inline" union:"member"`
	UnknownRaw     json.RawMessage `json:"-" union:"unknown"`

	Type EvalRunSummaryEndpointType
}

func CreateEvalRunSummaryEndpointPublicEndpoint(publicEndpoint PublicEndpoint) EvalRunSummaryEndpoint {
	typ := EvalRunSummaryEndpointTypePublicEndpoint

	return EvalRunSummaryEndpoint{
		PublicEndpoint: &publicEndpoint,
		Type:           typ,
	}
}

func CreateEvalRunSummaryEndpointMapOfAny(mapOfAny map[string]any) EvalRunSummaryEndpoint {
	typ := EvalRunSummaryEndpointTypeMapOfAny

	return EvalRunSummaryEndpoint{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateEvalRunSummaryEndpointUnknown(raw json.RawMessage) EvalRunSummaryEndpoint {
	return EvalRunSummaryEndpoint{
		UnknownRaw: raw,
		Type:       EvalRunSummaryEndpointTypeUnknown,
	}
}

func (u EvalRunSummaryEndpoint) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u EvalRunSummaryEndpoint) IsUnknown() bool {
	return u.Type == EvalRunSummaryEndpointTypeUnknown
}

func (u *EvalRunSummaryEndpoint) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var publicEndpoint PublicEndpoint = PublicEndpoint{}
	if err := utils.UnmarshalJSON(data, &publicEndpoint, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EvalRunSummaryEndpointTypePublicEndpoint,
			Value: &publicEndpoint,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  EvalRunSummaryEndpointTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = EvalRunSummaryEndpointTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = EvalRunSummaryEndpointTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(EvalRunSummaryEndpointType)
	switch best.Type {
	case EvalRunSummaryEndpointTypePublicEndpoint:
		u.PublicEndpoint = best.Value.(*PublicEndpoint)
		return nil
	case EvalRunSummaryEndpointTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = EvalRunSummaryEndpointTypeUnknown
	return nil
}

func (u EvalRunSummaryEndpoint) MarshalJSON() ([]byte, error) {
	if u.PublicEndpoint != nil {
		return utils.MarshalJSON(u.PublicEndpoint, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type EvalRunSummaryEndpoint: all fields are null")
}

type EvalRunSummary struct {
	ID             string                                                    `json:"id"`
	Endpoint       optionalnullable.OptionalNullable[EvalRunSummaryEndpoint] `json:"endpoint,omitzero"`
	Source         optionalnullable.OptionalNullable[EvalRunSource]          `json:"source,omitzero"`
	EvalType       optionalnullable.OptionalNullable[string]                 `json:"eval_type,omitzero"`
	Model          optionalnullable.OptionalNullable[string]                 `json:"model,omitzero"`
	ModelType      optionalnullable.OptionalNullable[string]                 `json:"model_type,omitzero"`
	Platform       optionalnullable.OptionalNullable[string]                 `json:"platform,omitzero"`
	Passed         optionalnullable.OptionalNullable[bool]                   `json:"passed,omitzero"`
	Score          optionalnullable.OptionalNullable[float64]                `json:"score,omitzero"`
	FailureReasons optionalnullable.OptionalNullable[[]string]               `json:"failure_reasons,omitzero"`
	LatencyMs      optionalnullable.OptionalNullable[int64]                  `json:"latency_ms,omitzero"`
	RunAt          optionalnullable.OptionalNullable[string]                 `json:"run_at,omitzero"`
}

func (e EvalRunSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvalRunSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvalRunSummary) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EvalRunSummary) GetEndpoint() optionalnullable.OptionalNullable[EvalRunSummaryEndpoint] {
	if e == nil {
		return nil
	}
	return e.Endpoint
}

func (e *EvalRunSummary) GetSource() optionalnullable.OptionalNullable[EvalRunSource] {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *EvalRunSummary) GetEvalType() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.EvalType
}

func (e *EvalRunSummary) GetModel() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Model
}

func (e *EvalRunSummary) GetModelType() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ModelType
}

func (e *EvalRunSummary) GetPlatform() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Platform
}

func (e *EvalRunSummary) GetPassed() optionalnullable.OptionalNullable[bool] {
	if e == nil {
		return nil
	}
	return e.Passed
}

func (e *EvalRunSummary) GetScore() optionalnullable.OptionalNullable[float64] {
	if e == nil {
		return nil
	}
	return e.Score
}

func (e *EvalRunSummary) GetFailureReasons() optionalnullable.OptionalNullable[[]string] {
	if e == nil {
		return nil
	}
	return e.FailureReasons
}

func (e *EvalRunSummary) GetLatencyMs() optionalnullable.OptionalNullable[int64] {
	if e == nil {
		return nil
	}
	return e.LatencyMs
}

func (e *EvalRunSummary) GetRunAt() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.RunAt
}
