// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f8f65220d6a1

package components

type EvalRunResponse struct {
	Data EvalRunDetail `json:"data"`
}

func (e *EvalRunResponse) GetData() EvalRunDetail {
	if e == nil {
		return EvalRunDetail{}
	}
	return e.Data
}
