// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvalRunsListResponse struct {
	Company PublicCompany    `json:"company"`
	Data    []EvalRunSummary `json:"data"`
	Meta    PublicListMeta   `json:"meta"`
}

func (e *EvalRunsListResponse) GetCompany() PublicCompany {
	if e == nil {
		return PublicCompany{}
	}
	return e.Company
}

func (e *EvalRunsListResponse) GetData() []EvalRunSummary {
	if e == nil {
		return []EvalRunSummary{}
	}
	return e.Data
}

func (e *EvalRunsListResponse) GetMeta() PublicListMeta {
	if e == nil {
		return PublicListMeta{}
	}
	return e.Meta
}
