// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 45e789e11ae8

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type FailureAnalysisSnapshot struct {
	TotalRuns               *int64                                     `default:"0" json:"total_runs"`
	FailedRuns              *int64                                     `default:"0" json:"failed_runs"`
	FailureRate             optionalnullable.OptionalNullable[float64] `json:"failure_rate,omitzero"`
	Patterns                []FailurePatternSnapshot                   `json:"patterns,omitzero"`
	TopFailureReasons       []map[string]any                           `json:"top_failure_reasons,omitzero"`
	EndpointsByFailureCount []map[string]any                           `json:"endpoints_by_failure_count,omitzero"`
}

func (f FailureAnalysisSnapshot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FailureAnalysisSnapshot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FailureAnalysisSnapshot) GetTotalRuns() *int64 {
	if f == nil {
		return nil
	}
	return f.TotalRuns
}

func (f *FailureAnalysisSnapshot) GetFailedRuns() *int64 {
	if f == nil {
		return nil
	}
	return f.FailedRuns
}

func (f *FailureAnalysisSnapshot) GetFailureRate() optionalnullable.OptionalNullable[float64] {
	if f == nil {
		return nil
	}
	return f.FailureRate
}

func (f *FailureAnalysisSnapshot) GetPatterns() []FailurePatternSnapshot {
	if f == nil {
		return nil
	}
	return f.Patterns
}

func (f *FailureAnalysisSnapshot) GetTopFailureReasons() []map[string]any {
	if f == nil {
		return nil
	}
	return f.TopFailureReasons
}

func (f *FailureAnalysisSnapshot) GetEndpointsByFailureCount() []map[string]any {
	if f == nil {
		return nil
	}
	return f.EndpointsByFailureCount
}
