// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PromptBatchError struct {
	Index int64  `json:"index"`
	Text  string `json:"text"`
	Error string `json:"error"`
}

func (p *PromptBatchError) GetIndex() int64 {
	if p == nil {
		return 0
	}
	return p.Index
}

func (p *PromptBatchError) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}

func (p *PromptBatchError) GetError() string {
	if p == nil {
		return ""
	}
	return p.Error
}
