// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type Tag string

const (
	TagCitedPages    Tag = "cited_pages"
	TagOpportunities Tag = "opportunities"
	TagAll           Tag = "all"
)

func (e Tag) ToPointer() *Tag {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Tag) IsExact() bool {
	if e != nil {
		switch *e {
		case "cited_pages", "opportunities", "all":
			return true
		}
	}
	return false
}

type PromptActionablesResponse struct {
	StartDate        string                    `json:"start_date"`
	EndDate          string                    `json:"end_date"`
	Tag              *Tag                      `default:"all" json:"tag"`
	Opportunities    []PublicPromptOpportunity `json:"opportunities,omitzero"`
	OpportunityCount int64                     `json:"opportunity_count"`
	CitedPages       []PublicCitedPage         `json:"cited_pages,omitzero"`
	CitedPageCount   int64                     `json:"cited_page_count"`
	Summary          map[string]any            `json:"summary,omitzero"`
}

func (p PromptActionablesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptActionablesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptActionablesResponse) GetStartDate() string {
	if p == nil {
		return ""
	}
	return p.StartDate
}

func (p *PromptActionablesResponse) GetEndDate() string {
	if p == nil {
		return ""
	}
	return p.EndDate
}

func (p *PromptActionablesResponse) GetTag() *Tag {
	if p == nil {
		return nil
	}
	return p.Tag
}

func (p *PromptActionablesResponse) GetOpportunities() []PublicPromptOpportunity {
	if p == nil {
		return nil
	}
	return p.Opportunities
}

func (p *PromptActionablesResponse) GetOpportunityCount() int64 {
	if p == nil {
		return 0
	}
	return p.OpportunityCount
}

func (p *PromptActionablesResponse) GetCitedPages() []PublicCitedPage {
	if p == nil {
		return nil
	}
	return p.CitedPages
}

func (p *PromptActionablesResponse) GetCitedPageCount() int64 {
	if p == nil {
		return 0
	}
	return p.CitedPageCount
}

func (p *PromptActionablesResponse) GetSummary() map[string]any {
	if p == nil {
		return nil
	}
	return p.Summary
}
