// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 975efc51b2ee

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalsResponse struct {
	Data []PublicCustomEval `json:"data"`
	Meta map[string]any     `json:"meta,omitzero"`
}

func (p PublicCustomEvalsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalsResponse) GetData() []PublicCustomEval {
	if p == nil {
		return []PublicCustomEval{}
	}
	return p.Data
}

func (p *PublicCustomEvalsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
