// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicPromptPlatformCostEstimate struct {
	CreditsPerPrompt int64 `json:"credits_per_prompt"`
	PromptCount      int64 `json:"prompt_count"`
	TotalCredits     int64 `json:"total_credits"`
}

func (p *PublicPromptPlatformCostEstimate) GetCreditsPerPrompt() int64 {
	if p == nil {
		return 0
	}
	return p.CreditsPerPrompt
}

func (p *PublicPromptPlatformCostEstimate) GetPromptCount() int64 {
	if p == nil {
		return 0
	}
	return p.PromptCount
}

func (p *PublicPromptPlatformCostEstimate) GetTotalCredits() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCredits
}
