// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f428ed24b26a

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceSourcesResponse struct {
	Data []PublicAPIPerformanceSource `json:"data"`
	Meta map[string]any               `json:"meta,omitzero"`
}

func (p PublicAPIPerformanceSourcesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceSourcesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceSourcesResponse) GetData() []PublicAPIPerformanceSource {
	if p == nil {
		return []PublicAPIPerformanceSource{}
	}
	return p.Data
}

func (p *PublicAPIPerformanceSourcesResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
