// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicStartingProjectsResponse struct {
	Data []PublicStartingProject `json:"data"`
	Meta map[string]any          `json:"meta,omitzero"`
}

func (p PublicStartingProjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicStartingProjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicStartingProjectsResponse) GetData() []PublicStartingProject {
	if p == nil {
		return []PublicStartingProject{}
	}
	return p.Data
}

func (p *PublicStartingProjectsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
