// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f0184774f7b5

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalEnvProfileSummary struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	EnvVarKeys []string `json:"env_var_keys,omitzero"`
}

func (p PublicEvalEnvProfileSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalEnvProfileSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalEnvProfileSummary) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicEvalEnvProfileSummary) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicEvalEnvProfileSummary) GetEnvVarKeys() []string {
	if p == nil {
		return nil
	}
	return p.EnvVarKeys
}
