// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c525badea499

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicPromptStatus string

const (
	PublicPromptStatusActive   PublicPromptStatus = "active"
	PublicPromptStatusInactive PublicPromptStatus = "inactive"
	PublicPromptStatusArchived PublicPromptStatus = "archived"
)

func (e PublicPromptStatus) ToPointer() *PublicPromptStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicPromptStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive", "archived":
			return true
		}
	}
	return false
}

type PublicPrompt struct {
	ID         string                                                `json:"id"`
	TopicID    string                                                `json:"topic_id"`
	Text       string                                                `json:"text"`
	LanguageID optionalnullable.OptionalNullable[string]             `json:"language_id,omitzero"`
	RegionID   optionalnullable.OptionalNullable[string]             `json:"region_id,omitzero"`
	IsActive   *bool                                                 `default:"true" json:"is_active"`
	Status     optionalnullable.OptionalNullable[PublicPromptStatus] `json:"status,omitzero"`
	Topic      optionalnullable.OptionalNullable[PublicPromptTopic]  `json:"topic,omitzero"`
	Platforms  []PublicPromptPlatform                                `json:"platforms,omitzero"`
	Tags       []PublicPromptTag                                     `json:"tags,omitzero"`
	CreatedAt  optionalnullable.OptionalNullable[string]             `json:"created_at,omitzero"`
	UpdatedAt  optionalnullable.OptionalNullable[string]             `json:"updated_at,omitzero"`
}

func (p PublicPrompt) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicPrompt) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicPrompt) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicPrompt) GetTopicID() string {
	if p == nil {
		return ""
	}
	return p.TopicID
}

func (p *PublicPrompt) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}

func (p *PublicPrompt) GetLanguageID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LanguageID
}

func (p *PublicPrompt) GetRegionID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.RegionID
}

func (p *PublicPrompt) GetIsActive() *bool {
	if p == nil {
		return nil
	}
	return p.IsActive
}

func (p *PublicPrompt) GetStatus() optionalnullable.OptionalNullable[PublicPromptStatus] {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PublicPrompt) GetTopic() optionalnullable.OptionalNullable[PublicPromptTopic] {
	if p == nil {
		return nil
	}
	return p.Topic
}

func (p *PublicPrompt) GetPlatforms() []PublicPromptPlatform {
	if p == nil {
		return nil
	}
	return p.Platforms
}

func (p *PublicPrompt) GetTags() []PublicPromptTag {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PublicPrompt) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicPrompt) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
