// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalDefinitionsResponse struct {
	Data []PublicEvalDefinition `json:"data"`
	Meta map[string]any         `json:"meta,omitzero"`
}

func (p PublicEvalDefinitionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalDefinitionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalDefinitionsResponse) GetData() []PublicEvalDefinition {
	if p == nil {
		return []PublicEvalDefinition{}
	}
	return p.Data
}

func (p *PublicEvalDefinitionsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
