// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type PublicActionDetailResponse struct {
	Data   PublicAPIPerformanceAction                `json:"data"`
	Prompt optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
}

func (p *PublicActionDetailResponse) GetData() PublicAPIPerformanceAction {
	if p == nil {
		return PublicAPIPerformanceAction{}
	}
	return p.Data
}

func (p *PublicActionDetailResponse) GetPrompt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Prompt
}
