// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalEnvProfileRequest struct {
	ID      string            `json:"id"`
	Name    string            `json:"name"`
	EnvVars map[string]string `json:"env_vars,omitzero"`
}

func (p PublicEvalEnvProfileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalEnvProfileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalEnvProfileRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicEvalEnvProfileRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicEvalEnvProfileRequest) GetEnvVars() map[string]string {
	if p == nil {
		return nil
	}
	return p.EnvVars
}
