// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7dc958334d02

package components

type PublicCustomEvalHistoryFilterOption struct {
	Value string `json:"value"`
	Label string `json:"label"`
	Count int64  `json:"count"`
}

func (p *PublicCustomEvalHistoryFilterOption) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *PublicCustomEvalHistoryFilterOption) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PublicCustomEvalHistoryFilterOption) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
