// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c02f05462fff

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type PublicPromptPlatformCatalogItem struct {
	ID               string                                    `json:"id"`
	Name             string                                    `json:"name"`
	Model            optionalnullable.OptionalNullable[string] `json:"model,omitzero"`
	CreditsPerPrompt int64                                     `json:"credits_per_prompt"`
}

func (p *PublicPromptPlatformCatalogItem) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicPromptPlatformCatalogItem) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicPromptPlatformCatalogItem) GetModel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PublicPromptPlatformCatalogItem) GetCreditsPerPrompt() int64 {
	if p == nil {
		return 0
	}
	return p.CreditsPerPrompt
}
