// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicPromptOpportunity struct {
	ID                   string         `json:"id"`
	Type                 string         `json:"type"`
	Category             string         `json:"category"`
	Priority             string         `json:"priority"`
	Title                string         `json:"title"`
	Description          string         `json:"description"`
	Action               string         `json:"action"`
	ImpactScore          float64        `json:"impact_score"`
	CreatedAt            string         `json:"created_at"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (p PublicPromptOpportunity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicPromptOpportunity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicPromptOpportunity) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicPromptOpportunity) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PublicPromptOpportunity) GetCategory() string {
	if p == nil {
		return ""
	}
	return p.Category
}

func (p *PublicPromptOpportunity) GetPriority() string {
	if p == nil {
		return ""
	}
	return p.Priority
}

func (p *PublicPromptOpportunity) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *PublicPromptOpportunity) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *PublicPromptOpportunity) GetAction() string {
	if p == nil {
		return ""
	}
	return p.Action
}

func (p *PublicPromptOpportunity) GetImpactScore() float64 {
	if p == nil {
		return 0.0
	}
	return p.ImpactScore
}

func (p *PublicPromptOpportunity) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *PublicPromptOpportunity) GetAdditionalProperties() map[string]any {
	if p == nil {
		return nil
	}
	return p.AdditionalProperties
}
