// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd3706f42c26

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicRefreshActionsRequest struct {
	IntegrationID optionalnullable.OptionalNullable[string] `json:"integration_id,omitzero"`
	Force         *bool                                     `default:"false" json:"force"`
}

func (p PublicRefreshActionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicRefreshActionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicRefreshActionsRequest) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.IntegrationID
}

func (p *PublicRefreshActionsRequest) GetForce() *bool {
	if p == nil {
		return nil
	}
	return p.Force
}
