// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceResultsResponse struct {
	BrandID         string                                            `json:"brand_id"`
	LatestRuns      map[string]any                                    `json:"latest_runs,omitzero"`
	FailureAnalysis map[string]any                                    `json:"failure_analysis,omitzero"`
	DocsAudit       optionalnullable.OptionalNullable[map[string]any] `json:"docs_audit,omitzero"`
	Meta            map[string]any                                    `json:"meta,omitzero"`
}

func (p PublicAPIPerformanceResultsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceResultsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceResultsResponse) GetBrandID() string {
	if p == nil {
		return ""
	}
	return p.BrandID
}

func (p *PublicAPIPerformanceResultsResponse) GetLatestRuns() map[string]any {
	if p == nil {
		return nil
	}
	return p.LatestRuns
}

func (p *PublicAPIPerformanceResultsResponse) GetFailureAnalysis() map[string]any {
	if p == nil {
		return nil
	}
	return p.FailureAnalysis
}

func (p *PublicAPIPerformanceResultsResponse) GetDocsAudit() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.DocsAudit
}

func (p *PublicAPIPerformanceResultsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
