// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9eaec7d55895

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalHistoryFacets struct {
	Targets    []PublicCustomEvalHistoryFilterOption `json:"targets,omitzero"`
	Categories []PublicCustomEvalHistoryFilterOption `json:"categories,omitzero"`
}

func (p PublicCustomEvalHistoryFacets) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalHistoryFacets) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalHistoryFacets) GetTargets() []PublicCustomEvalHistoryFilterOption {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicCustomEvalHistoryFacets) GetCategories() []PublicCustomEvalHistoryFilterOption {
	if p == nil {
		return nil
	}
	return p.Categories
}
