// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicVerifyActionResponse struct {
	Status   string                                                        `json:"status"`
	Action   optionalnullable.OptionalNullable[PublicAPIPerformanceAction] `json:"action,omitzero"`
	URLCheck optionalnullable.OptionalNullable[map[string]any]             `json:"url_check,omitzero"`
}

func (p PublicVerifyActionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicVerifyActionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicVerifyActionResponse) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PublicVerifyActionResponse) GetAction() optionalnullable.OptionalNullable[PublicAPIPerformanceAction] {
	if p == nil {
		return nil
	}
	return p.Action
}

func (p *PublicVerifyActionResponse) GetURLCheck() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.URLCheck
}
