// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 73a096a43366

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalRequest struct {
	Prompt string `json:"prompt"`
	// Optional template used to render prompt before storing. Available variables: Company name {{company_name}}; Company domain {{company_domain}}.
	PromptTemplate *string `json:"prompt_template,omitzero"`
	CategoryName   *string `json:"category_name,omitzero"`
	Description    *string `json:"description,omitzero"`
	// Competitor ID to render this custom eval against.
	Competitor *string `json:"competitor,omitzero"`
	// Base custom eval ID that this competitor variant belongs to.
	PromptCompetitorGroup *string                                                       `json:"prompt_competitor_group,omitzero"`
	Eval                  optionalnullable.OptionalNullable[PublicEvalDefinitionUpdate] `json:"eval,omitzero"`
}

func (p PublicCustomEvalRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalRequest) GetPrompt() string {
	if p == nil {
		return ""
	}
	return p.Prompt
}

func (p *PublicCustomEvalRequest) GetPromptTemplate() *string {
	if p == nil {
		return nil
	}
	return p.PromptTemplate
}

func (p *PublicCustomEvalRequest) GetCategoryName() *string {
	if p == nil {
		return nil
	}
	return p.CategoryName
}

func (p *PublicCustomEvalRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicCustomEvalRequest) GetCompetitor() *string {
	if p == nil {
		return nil
	}
	return p.Competitor
}

func (p *PublicCustomEvalRequest) GetPromptCompetitorGroup() *string {
	if p == nil {
		return nil
	}
	return p.PromptCompetitorGroup
}

func (p *PublicCustomEvalRequest) GetEval() optionalnullable.OptionalNullable[PublicEvalDefinitionUpdate] {
	if p == nil {
		return nil
	}
	return p.Eval
}
