// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalDefinitionUpdateDocsMode string

const (
	PublicEvalDefinitionUpdateDocsModeDefault PublicEvalDefinitionUpdateDocsMode = "default"
	PublicEvalDefinitionUpdateDocsModeInclude PublicEvalDefinitionUpdateDocsMode = "include"
	PublicEvalDefinitionUpdateDocsModeExclude PublicEvalDefinitionUpdateDocsMode = "exclude"
)

func (e PublicEvalDefinitionUpdateDocsMode) ToPointer() *PublicEvalDefinitionUpdateDocsMode {
	return &e
}
func (e *PublicEvalDefinitionUpdateDocsMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		fallthrough
	case "include":
		fallthrough
	case "exclude":
		*e = PublicEvalDefinitionUpdateDocsMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicEvalDefinitionUpdateDocsMode: %v", v)
	}
}

type PublicEvalDefinitionUpdateSkillsMode string

const (
	PublicEvalDefinitionUpdateSkillsModeNone     PublicEvalDefinitionUpdateSkillsMode = "none"
	PublicEvalDefinitionUpdateSkillsModeAll      PublicEvalDefinitionUpdateSkillsMode = "all"
	PublicEvalDefinitionUpdateSkillsModeSelected PublicEvalDefinitionUpdateSkillsMode = "selected"
)

func (e PublicEvalDefinitionUpdateSkillsMode) ToPointer() *PublicEvalDefinitionUpdateSkillsMode {
	return &e
}
func (e *PublicEvalDefinitionUpdateSkillsMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "all":
		fallthrough
	case "selected":
		*e = PublicEvalDefinitionUpdateSkillsMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicEvalDefinitionUpdateSkillsMode: %v", v)
	}
}

type PublicEvalDefinitionUpdate struct {
	CustomPrompt     optionalnullable.OptionalNullable[string] `json:"custom_prompt,omitzero"`
	ExpectedBehavior optionalnullable.OptionalNullable[string] `json:"expected_behavior,omitzero"`
	// Starting project to clone before running the eval. Empty string clears it.
	StartingProjectID optionalnullable.OptionalNullable[string] `json:"starting_project_id,omitzero"`
	// Legacy docs flag. Prefer docs_mode.
	IncludeBrandDocs optionalnullable.OptionalNullable[bool] `json:"include_brand_docs,omitzero"`
	// Docs behavior for this eval: default, include, or exclude.
	DocsMode optionalnullable.OptionalNullable[PublicEvalDefinitionUpdateDocsMode] `json:"docs_mode,omitzero"`
	// Include configured environment variable names in the eval prompt.
	IncludeEnvVars optionalnullable.OptionalNullable[bool] `json:"include_env_vars,omitzero"`
	// Environment profile IDs to use for this eval. Empty list clears the selection.
	EnvProfileIds optionalnullable.OptionalNullable[[]string] `json:"env_profile_ids,omitzero"`
	// Model IDs to use for this eval. Empty list uses the config-level models.
	ModelIds      optionalnullable.OptionalNullable[[]string]                             `json:"model_ids,omitzero"`
	CompareSkills optionalnullable.OptionalNullable[bool]                                 `json:"compare_skills,omitzero"`
	SkillsMode    optionalnullable.OptionalNullable[PublicEvalDefinitionUpdateSkillsMode] `json:"skills_mode,omitzero"`
	// Selected skill IDs. Used when skills_mode is selected.
	SkillIds   optionalnullable.OptionalNullable[[]string]       `json:"skill_ids,omitzero"`
	McpEnabled optionalnullable.OptionalNullable[bool]           `json:"mcp_enabled,omitzero"`
	RunContext optionalnullable.OptionalNullable[map[string]any] `json:"run_context,omitzero"`
	Enabled    optionalnullable.OptionalNullable[bool]           `json:"enabled,omitzero"`
}

func (p PublicEvalDefinitionUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalDefinitionUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalDefinitionUpdate) GetCustomPrompt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CustomPrompt
}

func (p *PublicEvalDefinitionUpdate) GetExpectedBehavior() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ExpectedBehavior
}

func (p *PublicEvalDefinitionUpdate) GetStartingProjectID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.StartingProjectID
}

func (p *PublicEvalDefinitionUpdate) GetIncludeBrandDocs() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.IncludeBrandDocs
}

func (p *PublicEvalDefinitionUpdate) GetDocsMode() optionalnullable.OptionalNullable[PublicEvalDefinitionUpdateDocsMode] {
	if p == nil {
		return nil
	}
	return p.DocsMode
}

func (p *PublicEvalDefinitionUpdate) GetIncludeEnvVars() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.IncludeEnvVars
}

func (p *PublicEvalDefinitionUpdate) GetEnvProfileIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.EnvProfileIds
}

func (p *PublicEvalDefinitionUpdate) GetModelIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.ModelIds
}

func (p *PublicEvalDefinitionUpdate) GetCompareSkills() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.CompareSkills
}

func (p *PublicEvalDefinitionUpdate) GetSkillsMode() optionalnullable.OptionalNullable[PublicEvalDefinitionUpdateSkillsMode] {
	if p == nil {
		return nil
	}
	return p.SkillsMode
}

func (p *PublicEvalDefinitionUpdate) GetSkillIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.SkillIds
}

func (p *PublicEvalDefinitionUpdate) GetMcpEnabled() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.McpEnabled
}

func (p *PublicEvalDefinitionUpdate) GetRunContext() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.RunContext
}

func (p *PublicEvalDefinitionUpdate) GetEnabled() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.Enabled
}
