// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a22063570d1e

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceActionsResponse struct {
	Data    []PublicAPIPerformanceAction `json:"data"`
	Counts  map[string]any               `json:"counts,omitzero"`
	Summary map[string]any               `json:"summary,omitzero"`
}

func (p PublicAPIPerformanceActionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceActionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceActionsResponse) GetData() []PublicAPIPerformanceAction {
	if p == nil {
		return []PublicAPIPerformanceAction{}
	}
	return p.Data
}

func (p *PublicAPIPerformanceActionsResponse) GetCounts() map[string]any {
	if p == nil {
		return nil
	}
	return p.Counts
}

func (p *PublicAPIPerformanceActionsResponse) GetSummary() map[string]any {
	if p == nil {
		return nil
	}
	return p.Summary
}
