// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0fe98e324e5f

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceTargetsResponseFrequency string

const (
	PublicAPIPerformanceTargetsResponseFrequencyDaily         PublicAPIPerformanceTargetsResponseFrequency = "daily"
	PublicAPIPerformanceTargetsResponseFrequencyEveryOtherDay PublicAPIPerformanceTargetsResponseFrequency = "every_other_day"
	PublicAPIPerformanceTargetsResponseFrequencyWeekly        PublicAPIPerformanceTargetsResponseFrequency = "weekly"
	PublicAPIPerformanceTargetsResponseFrequencyManual        PublicAPIPerformanceTargetsResponseFrequency = "manual"
)

func (e PublicAPIPerformanceTargetsResponseFrequency) ToPointer() *PublicAPIPerformanceTargetsResponseFrequency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicAPIPerformanceTargetsResponseFrequency) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "every_other_day", "weekly", "manual":
			return true
		}
	}
	return false
}

type PublicAPIPerformanceTargetsResponse struct {
	TextModels   []PublicAPIPerformanceTextModel                `json:"text_models"`
	CodingAgents []PublicAPIPerformanceCodingAgent              `json:"coding_agents"`
	Frequencies  []PublicAPIPerformanceTargetsResponseFrequency `json:"frequencies"`
	Meta         map[string]any                                 `json:"meta,omitzero"`
}

func (p PublicAPIPerformanceTargetsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceTargetsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceTargetsResponse) GetTextModels() []PublicAPIPerformanceTextModel {
	if p == nil {
		return []PublicAPIPerformanceTextModel{}
	}
	return p.TextModels
}

func (p *PublicAPIPerformanceTargetsResponse) GetCodingAgents() []PublicAPIPerformanceCodingAgent {
	if p == nil {
		return []PublicAPIPerformanceCodingAgent{}
	}
	return p.CodingAgents
}

func (p *PublicAPIPerformanceTargetsResponse) GetFrequencies() []PublicAPIPerformanceTargetsResponseFrequency {
	if p == nil {
		return []PublicAPIPerformanceTargetsResponseFrequency{}
	}
	return p.Frequencies
}

func (p *PublicAPIPerformanceTargetsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
