// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d68028f75acf

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalHistoryResponse struct {
	Runs            []PublicCustomEvalHistoryRun   `json:"runs"`
	Total           int64                          `json:"total"`
	Limit           int64                          `json:"limit"`
	Offset          int64                          `json:"offset"`
	HideInfraErrors *bool                          `default:"true" json:"hide_infra_errors"`
	Facets          *PublicCustomEvalHistoryFacets `json:"facets,omitzero"`
}

func (p PublicCustomEvalHistoryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalHistoryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalHistoryResponse) GetRuns() []PublicCustomEvalHistoryRun {
	if p == nil {
		return []PublicCustomEvalHistoryRun{}
	}
	return p.Runs
}

func (p *PublicCustomEvalHistoryResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PublicCustomEvalHistoryResponse) GetLimit() int64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PublicCustomEvalHistoryResponse) GetOffset() int64 {
	if p == nil {
		return 0
	}
	return p.Offset
}

func (p *PublicCustomEvalHistoryResponse) GetHideInfraErrors() *bool {
	if p == nil {
		return nil
	}
	return p.HideInfraErrors
}

func (p *PublicCustomEvalHistoryResponse) GetFacets() *PublicCustomEvalHistoryFacets {
	if p == nil {
		return nil
	}
	return p.Facets
}
