// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicOperationPrompt struct {
	ID               string                                    `json:"id"`
	OperationID      string                                    `json:"operation_id"`
	EvalType         string                                    `json:"eval_type"`
	Prompt           string                                    `json:"prompt"`
	ExpectedBehavior optionalnullable.OptionalNullable[string] `json:"expected_behavior,omitzero"`
	Graders          []map[string]any                          `json:"graders,omitzero"`
	ReferenceAnswer  optionalnullable.OptionalNullable[string] `json:"reference_answer,omitzero"`
	Enabled          *bool                                     `default:"true" json:"enabled"`
	CreatedAt        optionalnullable.OptionalNullable[string] `json:"created_at,omitzero"`
}

func (p PublicOperationPrompt) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicOperationPrompt) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicOperationPrompt) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicOperationPrompt) GetOperationID() string {
	if p == nil {
		return ""
	}
	return p.OperationID
}

func (p *PublicOperationPrompt) GetEvalType() string {
	if p == nil {
		return ""
	}
	return p.EvalType
}

func (p *PublicOperationPrompt) GetPrompt() string {
	if p == nil {
		return ""
	}
	return p.Prompt
}

func (p *PublicOperationPrompt) GetExpectedBehavior() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ExpectedBehavior
}

func (p *PublicOperationPrompt) GetGraders() []map[string]any {
	if p == nil {
		return nil
	}
	return p.Graders
}

func (p *PublicOperationPrompt) GetReferenceAnswer() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ReferenceAnswer
}

func (p *PublicOperationPrompt) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PublicOperationPrompt) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}
