// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceSource struct {
	ID            string                                    `json:"id"`
	Type          string                                    `json:"type"`
	Label         string                                    `json:"label"`
	Metadata      map[string]any                            `json:"metadata,omitzero"`
	Targets       []map[string]any                          `json:"targets,omitzero"`
	EndpointCount *int64                                    `default:"0" json:"endpoint_count"`
	CreatedAt     optionalnullable.OptionalNullable[string] `json:"created_at,omitzero"`
}

func (p PublicAPIPerformanceSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceSource) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceSource) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PublicAPIPerformanceSource) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PublicAPIPerformanceSource) GetMetadata() map[string]any {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PublicAPIPerformanceSource) GetTargets() []map[string]any {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicAPIPerformanceSource) GetEndpointCount() *int64 {
	if p == nil {
		return nil
	}
	return p.EndpointCount
}

func (p *PublicAPIPerformanceSource) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}
