// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicAPIPerformanceCodingAgentModel struct {
	ID     string                         `json:"id"`
	Label  string                         `json:"label"`
	Target PublicAPIPerformanceTargetSpec `json:"target"`
}

func (p *PublicAPIPerformanceCodingAgentModel) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceCodingAgentModel) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PublicAPIPerformanceCodingAgentModel) GetTarget() PublicAPIPerformanceTargetSpec {
	if p == nil {
		return PublicAPIPerformanceTargetSpec{}
	}
	return p.Target
}
