// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicPromptCostEstimateResponse struct {
	Estimates    map[string]PublicPromptPlatformCostEstimate `json:"estimates"`
	TotalCredits int64                                       `json:"total_credits"`
}

func (p *PublicPromptCostEstimateResponse) GetEstimates() map[string]PublicPromptPlatformCostEstimate {
	if p == nil {
		return map[string]PublicPromptPlatformCostEstimate{}
	}
	return p.Estimates
}

func (p *PublicPromptCostEstimateResponse) GetTotalCredits() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCredits
}
