// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c96ca942f3e4

package components

type PublicPromptPlatform struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (p *PublicPromptPlatform) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicPromptPlatform) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}
