// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a5868b2f1064

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceSkill struct {
	ID             string                                            `json:"id"`
	SourceID       string                                            `json:"source_id"`
	BrandID        string                                            `json:"brand_id"`
	IntegrationID  optionalnullable.OptionalNullable[string]         `json:"integration_id,omitzero"`
	Slug           string                                            `json:"slug"`
	Name           string                                            `json:"name"`
	Description    optionalnullable.OptionalNullable[string]         `json:"description,omitzero"`
	Path           string                                            `json:"path"`
	EntrypointPath string                                            `json:"entrypoint_path"`
	ContentHash    optionalnullable.OptionalNullable[string]         `json:"content_hash,omitzero"`
	Enabled        bool                                              `json:"enabled"`
	Stale          bool                                              `json:"stale"`
	Metadata       map[string]any                                    `json:"metadata,omitzero"`
	Source         optionalnullable.OptionalNullable[map[string]any] `json:"source,omitzero"`
	CreatedAt      optionalnullable.OptionalNullable[string]         `json:"created_at,omitzero"`
	UpdatedAt      optionalnullable.OptionalNullable[string]         `json:"updated_at,omitzero"`
}

func (p PublicAPIPerformanceSkill) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceSkill) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceSkill) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceSkill) GetSourceID() string {
	if p == nil {
		return ""
	}
	return p.SourceID
}

func (p *PublicAPIPerformanceSkill) GetBrandID() string {
	if p == nil {
		return ""
	}
	return p.BrandID
}

func (p *PublicAPIPerformanceSkill) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.IntegrationID
}

func (p *PublicAPIPerformanceSkill) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PublicAPIPerformanceSkill) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicAPIPerformanceSkill) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicAPIPerformanceSkill) GetPath() string {
	if p == nil {
		return ""
	}
	return p.Path
}

func (p *PublicAPIPerformanceSkill) GetEntrypointPath() string {
	if p == nil {
		return ""
	}
	return p.EntrypointPath
}

func (p *PublicAPIPerformanceSkill) GetContentHash() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ContentHash
}

func (p *PublicAPIPerformanceSkill) GetEnabled() bool {
	if p == nil {
		return false
	}
	return p.Enabled
}

func (p *PublicAPIPerformanceSkill) GetStale() bool {
	if p == nil {
		return false
	}
	return p.Stale
}

func (p *PublicAPIPerformanceSkill) GetMetadata() map[string]any {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PublicAPIPerformanceSkill) GetSource() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.Source
}

func (p *PublicAPIPerformanceSkill) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicAPIPerformanceSkill) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
