// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df0bc5da6abb

package components

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceEvalRunTargetTargetType string

const (
	PublicAPIPerformanceEvalRunTargetTargetTypeText  PublicAPIPerformanceEvalRunTargetTargetType = "text"
	PublicAPIPerformanceEvalRunTargetTargetTypeAgent PublicAPIPerformanceEvalRunTargetTargetType = "agent"
)

func (e PublicAPIPerformanceEvalRunTargetTargetType) ToPointer() *PublicAPIPerformanceEvalRunTargetTargetType {
	return &e
}
func (e *PublicAPIPerformanceEvalRunTargetTargetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "agent":
		*e = PublicAPIPerformanceEvalRunTargetTargetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicAPIPerformanceEvalRunTargetTargetType: %v", v)
	}
}

type PublicAPIPerformanceEvalRunTarget struct {
	TargetType        PublicAPIPerformanceEvalRunTargetTargetType `json:"target_type"`
	ExecutionPlatform string                                      `json:"execution_platform"`
	ModelID           string                                      `json:"model_id"`
	Enabled           *bool                                       `default:"true" json:"enabled"`
}

func (p PublicAPIPerformanceEvalRunTarget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceEvalRunTarget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceEvalRunTarget) GetTargetType() PublicAPIPerformanceEvalRunTargetTargetType {
	if p == nil {
		return PublicAPIPerformanceEvalRunTargetTargetType("")
	}
	return p.TargetType
}

func (p *PublicAPIPerformanceEvalRunTarget) GetExecutionPlatform() string {
	if p == nil {
		return ""
	}
	return p.ExecutionPlatform
}

func (p *PublicAPIPerformanceEvalRunTarget) GetModelID() string {
	if p == nil {
		return ""
	}
	return p.ModelID
}

func (p *PublicAPIPerformanceEvalRunTarget) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}
