// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a5390c8f64a7

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicStartingProjectFramework string

const (
	PublicStartingProjectFrameworkFastify PublicStartingProjectFramework = "fastify"
	PublicStartingProjectFrameworkNuxt    PublicStartingProjectFramework = "nuxt"
	PublicStartingProjectFrameworkExpress PublicStartingProjectFramework = "express"
	PublicStartingProjectFrameworkSpaJs   PublicStartingProjectFramework = "spa-js"
	PublicStartingProjectFrameworkAngular PublicStartingProjectFramework = "angular"
	PublicStartingProjectFrameworkReact   PublicStartingProjectFramework = "react"
	PublicStartingProjectFrameworkFastapi PublicStartingProjectFramework = "fastapi"
	PublicStartingProjectFrameworkVite    PublicStartingProjectFramework = "vite"
	PublicStartingProjectFrameworkNextjs  PublicStartingProjectFramework = "nextjs"
	PublicStartingProjectFrameworkCustom  PublicStartingProjectFramework = "custom"
)

func (e PublicStartingProjectFramework) ToPointer() *PublicStartingProjectFramework {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicStartingProjectFramework) IsExact() bool {
	if e != nil {
		switch *e {
		case "fastify", "nuxt", "express", "spa-js", "angular", "react", "fastapi", "vite", "nextjs", "custom":
			return true
		}
	}
	return false
}

type PublicStartingProject struct {
	ID           string                                    `json:"id"`
	SourceID     optionalnullable.OptionalNullable[string] `json:"source_id,omitzero"`
	Name         string                                    `json:"name"`
	RepoURL      string                                    `json:"repo_url"`
	Ref          string                                    `json:"ref"`
	Subdir       *string                                   `default:"" json:"subdir"`
	InstallSteps []string                                  `json:"install_steps,omitzero"`
	Framework    *PublicStartingProjectFramework           `default:"custom" json:"framework"`
	Enabled      bool                                      `json:"enabled"`
	CreatedAt    optionalnullable.OptionalNullable[string] `json:"created_at,omitzero"`
	UpdatedAt    optionalnullable.OptionalNullable[string] `json:"updated_at,omitzero"`
}

func (p PublicStartingProject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicStartingProject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicStartingProject) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicStartingProject) GetSourceID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SourceID
}

func (p *PublicStartingProject) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicStartingProject) GetRepoURL() string {
	if p == nil {
		return ""
	}
	return p.RepoURL
}

func (p *PublicStartingProject) GetRef() string {
	if p == nil {
		return ""
	}
	return p.Ref
}

func (p *PublicStartingProject) GetSubdir() *string {
	if p == nil {
		return nil
	}
	return p.Subdir
}

func (p *PublicStartingProject) GetInstallSteps() []string {
	if p == nil {
		return nil
	}
	return p.InstallSteps
}

func (p *PublicStartingProject) GetFramework() *PublicStartingProjectFramework {
	if p == nil {
		return nil
	}
	return p.Framework
}

func (p *PublicStartingProject) GetEnabled() bool {
	if p == nil {
		return false
	}
	return p.Enabled
}

func (p *PublicStartingProject) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicStartingProject) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
