// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b80dc0f15857

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type PublicPromptRegion struct {
	ID          string                                    `json:"id"`
	Country     string                                    `json:"country"`
	CountryCode optionalnullable.OptionalNullable[string] `json:"country_code,omitzero"`
}

func (p *PublicPromptRegion) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicPromptRegion) GetCountry() string {
	if p == nil {
		return ""
	}
	return p.Country
}

func (p *PublicPromptRegion) GetCountryCode() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CountryCode
}
