// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type TargetType string

const (
	TargetTypeText  TargetType = "text"
	TargetTypeAgent TargetType = "agent"
)

func (e TargetType) ToPointer() *TargetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TargetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "agent":
			return true
		}
	}
	return false
}

type Frequency string

const (
	FrequencyDaily         Frequency = "daily"
	FrequencyEveryOtherDay Frequency = "every_other_day"
	FrequencyWeekly        Frequency = "weekly"
	FrequencyManual        Frequency = "manual"
)

func (e Frequency) ToPointer() *Frequency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Frequency) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "every_other_day", "weekly", "manual":
			return true
		}
	}
	return false
}

type PublicAPIEvalTarget struct {
	ID                optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	OrgID             optionalnullable.OptionalNullable[string] `json:"org_id,omitzero"`
	BrandID           optionalnullable.OptionalNullable[string] `json:"brand_id,omitzero"`
	IntegrationID     optionalnullable.OptionalNullable[string] `json:"integration_id,omitzero"`
	TargetType        TargetType                                `json:"target_type"`
	ExecutionPlatform string                                    `json:"execution_platform"`
	ModelID           string                                    `json:"model_id"`
	Frequency         *Frequency                                `default:"daily" json:"frequency"`
	Enabled           *bool                                     `default:"true" json:"enabled"`
	NextRunAt         optionalnullable.OptionalNullable[string] `json:"next_run_at,omitzero"`
	LastRunAt         optionalnullable.OptionalNullable[string] `json:"last_run_at,omitzero"`
	LastSkippedAt     optionalnullable.OptionalNullable[string] `json:"last_skipped_at,omitzero"`
	SkipReason        optionalnullable.OptionalNullable[string] `json:"skip_reason,omitzero"`
	CreatedAt         optionalnullable.OptionalNullable[string] `json:"created_at,omitzero"`
	UpdatedAt         optionalnullable.OptionalNullable[string] `json:"updated_at,omitzero"`
}

func (p PublicAPIEvalTarget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIEvalTarget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIEvalTarget) GetID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PublicAPIEvalTarget) GetOrgID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.OrgID
}

func (p *PublicAPIEvalTarget) GetBrandID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.BrandID
}

func (p *PublicAPIEvalTarget) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.IntegrationID
}

func (p *PublicAPIEvalTarget) GetTargetType() TargetType {
	if p == nil {
		return TargetType("")
	}
	return p.TargetType
}

func (p *PublicAPIEvalTarget) GetExecutionPlatform() string {
	if p == nil {
		return ""
	}
	return p.ExecutionPlatform
}

func (p *PublicAPIEvalTarget) GetModelID() string {
	if p == nil {
		return ""
	}
	return p.ModelID
}

func (p *PublicAPIEvalTarget) GetFrequency() *Frequency {
	if p == nil {
		return nil
	}
	return p.Frequency
}

func (p *PublicAPIEvalTarget) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PublicAPIEvalTarget) GetNextRunAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.NextRunAt
}

func (p *PublicAPIEvalTarget) GetLastRunAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LastRunAt
}

func (p *PublicAPIEvalTarget) GetLastSkippedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LastSkippedAt
}

func (p *PublicAPIEvalTarget) GetSkipReason() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SkipReason
}

func (p *PublicAPIEvalTarget) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicAPIEvalTarget) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
