// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df483292152c

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalUpdateRequest struct {
	Prompt *string `json:"prompt,omitzero"`
	// Optional template used to render prompt before storing. Available variables: Company name {{company_name}}; Company domain {{company_domain}}.
	PromptTemplate        *string                                                       `json:"prompt_template,omitzero"`
	CategoryName          *string                                                       `json:"category_name,omitzero"`
	Description           *string                                                       `json:"description,omitzero"`
	Competitor            *string                                                       `json:"competitor,omitzero"`
	PromptCompetitorGroup *string                                                       `json:"prompt_competitor_group,omitzero"`
	Eval                  optionalnullable.OptionalNullable[PublicEvalDefinitionUpdate] `json:"eval,omitzero"`
}

func (p PublicCustomEvalUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalUpdateRequest) GetPrompt() *string {
	if p == nil {
		return nil
	}
	return p.Prompt
}

func (p *PublicCustomEvalUpdateRequest) GetPromptTemplate() *string {
	if p == nil {
		return nil
	}
	return p.PromptTemplate
}

func (p *PublicCustomEvalUpdateRequest) GetCategoryName() *string {
	if p == nil {
		return nil
	}
	return p.CategoryName
}

func (p *PublicCustomEvalUpdateRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicCustomEvalUpdateRequest) GetCompetitor() *string {
	if p == nil {
		return nil
	}
	return p.Competitor
}

func (p *PublicCustomEvalUpdateRequest) GetPromptCompetitorGroup() *string {
	if p == nil {
		return nil
	}
	return p.PromptCompetitorGroup
}

func (p *PublicCustomEvalUpdateRequest) GetEval() optionalnullable.OptionalNullable[PublicEvalDefinitionUpdate] {
	if p == nil {
		return nil
	}
	return p.Eval
}
