// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceRun struct {
	ID               string                                      `json:"id"`
	EvalID           optionalnullable.OptionalNullable[string]   `json:"eval_id,omitzero"`
	EvalType         optionalnullable.OptionalNullable[string]   `json:"eval_type,omitzero"`
	Prompt           optionalnullable.OptionalNullable[string]   `json:"prompt,omitzero"`
	ExpectedBehavior optionalnullable.OptionalNullable[string]   `json:"expected_behavior,omitzero"`
	Graders          []map[string]any                            `json:"graders,omitzero"`
	ReferenceAnswer  optionalnullable.OptionalNullable[string]   `json:"reference_answer,omitzero"`
	Platform         optionalnullable.OptionalNullable[string]   `json:"platform,omitzero"`
	Model            optionalnullable.OptionalNullable[string]   `json:"model,omitzero"`
	ModelType        optionalnullable.OptionalNullable[string]   `json:"model_type,omitzero"`
	Passed           optionalnullable.OptionalNullable[bool]     `json:"passed,omitzero"`
	Score            optionalnullable.OptionalNullable[float64]  `json:"score,omitzero"`
	FailureReasons   optionalnullable.OptionalNullable[[]string] `json:"failure_reasons,omitzero"`
	ErrorMessage     optionalnullable.OptionalNullable[string]   `json:"error_message,omitzero"`
	LatencyMs        optionalnullable.OptionalNullable[int64]    `json:"latency_ms,omitzero"`
	TokensUsed       optionalnullable.OptionalNullable[int64]    `json:"tokens_used,omitzero"`
	RunDate          optionalnullable.OptionalNullable[string]   `json:"run_date,omitzero"`
	CreatedAt        optionalnullable.OptionalNullable[string]   `json:"created_at,omitzero"`
}

func (p PublicAPIPerformanceRun) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceRun) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceRun) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceRun) GetEvalID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.EvalID
}

func (p *PublicAPIPerformanceRun) GetEvalType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.EvalType
}

func (p *PublicAPIPerformanceRun) GetPrompt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Prompt
}

func (p *PublicAPIPerformanceRun) GetExpectedBehavior() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ExpectedBehavior
}

func (p *PublicAPIPerformanceRun) GetGraders() []map[string]any {
	if p == nil {
		return nil
	}
	return p.Graders
}

func (p *PublicAPIPerformanceRun) GetReferenceAnswer() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ReferenceAnswer
}

func (p *PublicAPIPerformanceRun) GetPlatform() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PublicAPIPerformanceRun) GetModel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PublicAPIPerformanceRun) GetModelType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ModelType
}

func (p *PublicAPIPerformanceRun) GetPassed() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.Passed
}

func (p *PublicAPIPerformanceRun) GetScore() optionalnullable.OptionalNullable[float64] {
	if p == nil {
		return nil
	}
	return p.Score
}

func (p *PublicAPIPerformanceRun) GetFailureReasons() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.FailureReasons
}

func (p *PublicAPIPerformanceRun) GetErrorMessage() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ErrorMessage
}

func (p *PublicAPIPerformanceRun) GetLatencyMs() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.LatencyMs
}

func (p *PublicAPIPerformanceRun) GetTokensUsed() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.TokensUsed
}

func (p *PublicAPIPerformanceRun) GetRunDate() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.RunDate
}

func (p *PublicAPIPerformanceRun) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}
