// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 72acbbc4dfdf

package components

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceEvalRunRequestSourceType string

const (
	PublicAPIPerformanceEvalRunRequestSourceTypeRestAPI     PublicAPIPerformanceEvalRunRequestSourceType = "rest_api"
	PublicAPIPerformanceEvalRunRequestSourceTypeSDK         PublicAPIPerformanceEvalRunRequestSourceType = "sdk"
	PublicAPIPerformanceEvalRunRequestSourceTypeCli         PublicAPIPerformanceEvalRunRequestSourceType = "cli"
	PublicAPIPerformanceEvalRunRequestSourceTypeCustomEvals PublicAPIPerformanceEvalRunRequestSourceType = "custom_evals"
)

func (e PublicAPIPerformanceEvalRunRequestSourceType) ToPointer() *PublicAPIPerformanceEvalRunRequestSourceType {
	return &e
}
func (e *PublicAPIPerformanceEvalRunRequestSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rest_api":
		fallthrough
	case "sdk":
		fallthrough
	case "cli":
		fallthrough
	case "custom_evals":
		*e = PublicAPIPerformanceEvalRunRequestSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicAPIPerformanceEvalRunRequestSourceType: %v", v)
	}
}

type PublicAPIPerformanceEvalRunRequest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_      string                                       `const:"api_performance" json:"type"`
	SourceType PublicAPIPerformanceEvalRunRequestSourceType `json:"source_type"`
	// API Performance source ID from api-performance sources list. Required unless operation_ids, eval_ids, or source_type identify one source.
	SourceID *string `json:"source_id,omitzero"`
	// Legacy flat model selection. Prefer targets.
	Models optionalnullable.OptionalNullable[[]string] `json:"models,omitzero"`
	// Explicit text/agent targets to run.
	Targets    optionalnullable.OptionalNullable[[]PublicAPIPerformanceEvalRunTarget] `json:"targets,omitzero"`
	Categories optionalnullable.OptionalNullable[[]string]                            `json:"categories,omitzero"`
	// API Performance operation IDs from api-performance evals list.
	OperationIds optionalnullable.OptionalNullable[[]string] `json:"operation_ids,omitzero"`
	// Optional METHOD:path filters, such as GET:/v1/items.
	OperationPaths optionalnullable.OptionalNullable[[]string] `json:"operation_paths,omitzero"`
	// API Performance eval definition IDs from api-performance evals list.
	EvalIds optionalnullable.OptionalNullable[[]string] `json:"eval_ids,omitzero"`
	// Custom eval IDs. Used only when source_type is custom_evals.
	CustomEvalIds optionalnullable.OptionalNullable[[]string]                  `json:"custom_eval_ids,omitzero"`
	EvalTypes     optionalnullable.OptionalNullable[[]string]                  `json:"eval_types,omitzero"`
	EnvProfileIds optionalnullable.OptionalNullable[[]string]                  `json:"env_profile_ids,omitzero"`
	EvalOverrides optionalnullable.OptionalNullable[map[string]map[string]any] `json:"eval_overrides,omitzero"`
}

func (p PublicAPIPerformanceEvalRunRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceEvalRunRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceEvalRunRequest) GetType() string {
	return "api_performance"
}

func (p *PublicAPIPerformanceEvalRunRequest) GetSourceType() PublicAPIPerformanceEvalRunRequestSourceType {
	if p == nil {
		return PublicAPIPerformanceEvalRunRequestSourceType("")
	}
	return p.SourceType
}

func (p *PublicAPIPerformanceEvalRunRequest) GetSourceID() *string {
	if p == nil {
		return nil
	}
	return p.SourceID
}

func (p *PublicAPIPerformanceEvalRunRequest) GetModels() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Models
}

func (p *PublicAPIPerformanceEvalRunRequest) GetTargets() optionalnullable.OptionalNullable[[]PublicAPIPerformanceEvalRunTarget] {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicAPIPerformanceEvalRunRequest) GetCategories() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Categories
}

func (p *PublicAPIPerformanceEvalRunRequest) GetOperationIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.OperationIds
}

func (p *PublicAPIPerformanceEvalRunRequest) GetOperationPaths() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.OperationPaths
}

func (p *PublicAPIPerformanceEvalRunRequest) GetEvalIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.EvalIds
}

func (p *PublicAPIPerformanceEvalRunRequest) GetCustomEvalIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.CustomEvalIds
}

func (p *PublicAPIPerformanceEvalRunRequest) GetEvalTypes() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.EvalTypes
}

func (p *PublicAPIPerformanceEvalRunRequest) GetEnvProfileIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.EnvProfileIds
}

func (p *PublicAPIPerformanceEvalRunRequest) GetEvalOverrides() optionalnullable.OptionalNullable[map[string]map[string]any] {
	if p == nil {
		return nil
	}
	return p.EvalOverrides
}
