// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ddc459193e41

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type PublicAPIPerformanceSourceRef struct {
	ID    string                                    `json:"id"`
	Type  optionalnullable.OptionalNullable[string] `json:"type,omitzero"`
	Label optionalnullable.OptionalNullable[string] `json:"label,omitzero"`
}

func (p *PublicAPIPerformanceSourceRef) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceSourceRef) GetType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PublicAPIPerformanceSourceRef) GetLabel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Label
}
