// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f625c59e2bba

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalConfigUpdateRequest struct {
	// Legacy flat model selection. Prefer targets for v0.3.0.
	Models optionalnullable.OptionalNullable[[]string] `json:"models,omitzero"`
	// Scheduled text/agent targets. Use frequency='manual' to keep a target available but unscheduled.
	Targets             optionalnullable.OptionalNullable[[]PublicAPIEvalTarget]         `json:"targets,omitzero"`
	OperationIds        optionalnullable.OptionalNullable[[]string]                      `json:"operation_ids,omitzero"`
	CustomEvalIds       optionalnullable.OptionalNullable[[]string]                      `json:"custom_eval_ids,omitzero"`
	EnvVars             optionalnullable.OptionalNullable[map[string]string]             `json:"env_vars,omitzero"`
	EnvProfiles         optionalnullable.OptionalNullable[[]PublicEvalEnvProfileRequest] `json:"env_profiles,omitzero"`
	DefaultEnvProfileID *string                                                          `json:"default_env_profile_id,omitzero"`
	SourceID            *string                                                          `json:"source_id,omitzero"`
	APIBaseURL          *string                                                          `json:"api_base_url,omitzero"`
}

func (p PublicEvalConfigUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalConfigUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalConfigUpdateRequest) GetModels() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Models
}

func (p *PublicEvalConfigUpdateRequest) GetTargets() optionalnullable.OptionalNullable[[]PublicAPIEvalTarget] {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicEvalConfigUpdateRequest) GetOperationIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.OperationIds
}

func (p *PublicEvalConfigUpdateRequest) GetCustomEvalIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.CustomEvalIds
}

func (p *PublicEvalConfigUpdateRequest) GetEnvVars() optionalnullable.OptionalNullable[map[string]string] {
	if p == nil {
		return nil
	}
	return p.EnvVars
}

func (p *PublicEvalConfigUpdateRequest) GetEnvProfiles() optionalnullable.OptionalNullable[[]PublicEvalEnvProfileRequest] {
	if p == nil {
		return nil
	}
	return p.EnvProfiles
}

func (p *PublicEvalConfigUpdateRequest) GetDefaultEnvProfileID() *string {
	if p == nil {
		return nil
	}
	return p.DefaultEnvProfileID
}

func (p *PublicEvalConfigUpdateRequest) GetSourceID() *string {
	if p == nil {
		return nil
	}
	return p.SourceID
}

func (p *PublicEvalConfigUpdateRequest) GetAPIBaseURL() *string {
	if p == nil {
		return nil
	}
	return p.APIBaseURL
}
