// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicAPIPerformanceRunResponse struct {
	Operation PublicAPIPerformanceOperation `json:"operation"`
	Data      PublicAPIPerformanceRunDetail `json:"data"`
}

func (p *PublicAPIPerformanceRunResponse) GetOperation() PublicAPIPerformanceOperation {
	if p == nil {
		return PublicAPIPerformanceOperation{}
	}
	return p.Operation
}

func (p *PublicAPIPerformanceRunResponse) GetData() PublicAPIPerformanceRunDetail {
	if p == nil {
		return PublicAPIPerformanceRunDetail{}
	}
	return p.Data
}
