// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 415daf9f4546

package components

import (
	"encoding/json"
	"fmt"
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicStartingProjectUpdateRequestFramework string

const (
	PublicStartingProjectUpdateRequestFrameworkFastify PublicStartingProjectUpdateRequestFramework = "fastify"
	PublicStartingProjectUpdateRequestFrameworkNuxt    PublicStartingProjectUpdateRequestFramework = "nuxt"
	PublicStartingProjectUpdateRequestFrameworkExpress PublicStartingProjectUpdateRequestFramework = "express"
	PublicStartingProjectUpdateRequestFrameworkSpaJs   PublicStartingProjectUpdateRequestFramework = "spa-js"
	PublicStartingProjectUpdateRequestFrameworkAngular PublicStartingProjectUpdateRequestFramework = "angular"
	PublicStartingProjectUpdateRequestFrameworkReact   PublicStartingProjectUpdateRequestFramework = "react"
	PublicStartingProjectUpdateRequestFrameworkFastapi PublicStartingProjectUpdateRequestFramework = "fastapi"
	PublicStartingProjectUpdateRequestFrameworkVite    PublicStartingProjectUpdateRequestFramework = "vite"
	PublicStartingProjectUpdateRequestFrameworkNextjs  PublicStartingProjectUpdateRequestFramework = "nextjs"
	PublicStartingProjectUpdateRequestFrameworkCustom  PublicStartingProjectUpdateRequestFramework = "custom"
)

func (e PublicStartingProjectUpdateRequestFramework) ToPointer() *PublicStartingProjectUpdateRequestFramework {
	return &e
}
func (e *PublicStartingProjectUpdateRequestFramework) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fastify":
		fallthrough
	case "nuxt":
		fallthrough
	case "express":
		fallthrough
	case "spa-js":
		fallthrough
	case "angular":
		fallthrough
	case "react":
		fallthrough
	case "fastapi":
		fallthrough
	case "vite":
		fallthrough
	case "nextjs":
		fallthrough
	case "custom":
		*e = PublicStartingProjectUpdateRequestFramework(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicStartingProjectUpdateRequestFramework: %v", v)
	}
}

type PublicStartingProjectUpdateRequest struct {
	Name          optionalnullable.OptionalNullable[string]                                      `json:"name,omitzero"`
	RepoURL       optionalnullable.OptionalNullable[string]                                      `json:"repo_url,omitzero"`
	Ref           optionalnullable.OptionalNullable[string]                                      `json:"ref,omitzero"`
	Subdir        optionalnullable.OptionalNullable[string]                                      `json:"subdir,omitzero"`
	InstallSteps  optionalnullable.OptionalNullable[[]string]                                    `json:"install_steps,omitzero"`
	IntegrationID optionalnullable.OptionalNullable[string]                                      `json:"integration_id,omitzero"`
	Framework     optionalnullable.OptionalNullable[PublicStartingProjectUpdateRequestFramework] `json:"framework,omitzero"`
	Enabled       optionalnullable.OptionalNullable[bool]                                        `json:"enabled,omitzero"`
}

func (p PublicStartingProjectUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicStartingProjectUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicStartingProjectUpdateRequest) GetName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PublicStartingProjectUpdateRequest) GetRepoURL() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.RepoURL
}

func (p *PublicStartingProjectUpdateRequest) GetRef() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Ref
}

func (p *PublicStartingProjectUpdateRequest) GetSubdir() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Subdir
}

func (p *PublicStartingProjectUpdateRequest) GetInstallSteps() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.InstallSteps
}

func (p *PublicStartingProjectUpdateRequest) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.IntegrationID
}

func (p *PublicStartingProjectUpdateRequest) GetFramework() optionalnullable.OptionalNullable[PublicStartingProjectUpdateRequestFramework] {
	if p == nil {
		return nil
	}
	return p.Framework
}

func (p *PublicStartingProjectUpdateRequest) GetEnabled() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.Enabled
}
