// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicAPIPerformanceTargetSpecTargetType string

const (
	PublicAPIPerformanceTargetSpecTargetTypeText  PublicAPIPerformanceTargetSpecTargetType = "text"
	PublicAPIPerformanceTargetSpecTargetTypeAgent PublicAPIPerformanceTargetSpecTargetType = "agent"
)

func (e PublicAPIPerformanceTargetSpecTargetType) ToPointer() *PublicAPIPerformanceTargetSpecTargetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicAPIPerformanceTargetSpecTargetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "agent":
			return true
		}
	}
	return false
}

type PublicAPIPerformanceTargetSpec struct {
	TargetType        PublicAPIPerformanceTargetSpecTargetType `json:"target_type"`
	ExecutionPlatform string                                   `json:"execution_platform"`
	ModelID           string                                   `json:"model_id"`
}

func (p *PublicAPIPerformanceTargetSpec) GetTargetType() PublicAPIPerformanceTargetSpecTargetType {
	if p == nil {
		return PublicAPIPerformanceTargetSpecTargetType("")
	}
	return p.TargetType
}

func (p *PublicAPIPerformanceTargetSpec) GetExecutionPlatform() string {
	if p == nil {
		return ""
	}
	return p.ExecutionPlatform
}

func (p *PublicAPIPerformanceTargetSpec) GetModelID() string {
	if p == nil {
		return ""
	}
	return p.ModelID
}
