// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9613ce70d7cf

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIEvalTargetTargetType string

const (
	PublicAPIEvalTargetTargetTypeText  PublicAPIEvalTargetTargetType = "text"
	PublicAPIEvalTargetTargetTypeAgent PublicAPIEvalTargetTargetType = "agent"
)

func (e PublicAPIEvalTargetTargetType) ToPointer() *PublicAPIEvalTargetTargetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicAPIEvalTargetTargetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "agent":
			return true
		}
	}
	return false
}

type PublicAPIEvalTargetFrequency string

const (
	PublicAPIEvalTargetFrequencyDaily         PublicAPIEvalTargetFrequency = "daily"
	PublicAPIEvalTargetFrequencyEveryOtherDay PublicAPIEvalTargetFrequency = "every_other_day"
	PublicAPIEvalTargetFrequencyWeekly        PublicAPIEvalTargetFrequency = "weekly"
	PublicAPIEvalTargetFrequencyManual        PublicAPIEvalTargetFrequency = "manual"
)

func (e PublicAPIEvalTargetFrequency) ToPointer() *PublicAPIEvalTargetFrequency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PublicAPIEvalTargetFrequency) IsExact() bool {
	if e != nil {
		switch *e {
		case "daily", "every_other_day", "weekly", "manual":
			return true
		}
	}
	return false
}

type PublicAPIEvalTarget struct {
	ID                optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	IntegrationID     optionalnullable.OptionalNullable[string] `json:"integration_id,omitzero"`
	TargetType        PublicAPIEvalTargetTargetType             `json:"target_type"`
	ExecutionPlatform string                                    `json:"execution_platform"`
	ModelID           string                                    `json:"model_id"`
	Frequency         *PublicAPIEvalTargetFrequency             `default:"daily" json:"frequency"`
	Enabled           *bool                                     `default:"true" json:"enabled"`
	NextRunAt         optionalnullable.OptionalNullable[string] `json:"next_run_at,omitzero"`
	LastRunAt         optionalnullable.OptionalNullable[string] `json:"last_run_at,omitzero"`
	LastSkippedAt     optionalnullable.OptionalNullable[string] `json:"last_skipped_at,omitzero"`
	SkipReason        optionalnullable.OptionalNullable[string] `json:"skip_reason,omitzero"`
	CreatedAt         optionalnullable.OptionalNullable[string] `json:"created_at,omitzero"`
	UpdatedAt         optionalnullable.OptionalNullable[string] `json:"updated_at,omitzero"`
}

func (p PublicAPIEvalTarget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIEvalTarget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIEvalTarget) GetID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PublicAPIEvalTarget) GetIntegrationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.IntegrationID
}

func (p *PublicAPIEvalTarget) GetTargetType() PublicAPIEvalTargetTargetType {
	if p == nil {
		return PublicAPIEvalTargetTargetType("")
	}
	return p.TargetType
}

func (p *PublicAPIEvalTarget) GetExecutionPlatform() string {
	if p == nil {
		return ""
	}
	return p.ExecutionPlatform
}

func (p *PublicAPIEvalTarget) GetModelID() string {
	if p == nil {
		return ""
	}
	return p.ModelID
}

func (p *PublicAPIEvalTarget) GetFrequency() *PublicAPIEvalTargetFrequency {
	if p == nil {
		return nil
	}
	return p.Frequency
}

func (p *PublicAPIEvalTarget) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PublicAPIEvalTarget) GetNextRunAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.NextRunAt
}

func (p *PublicAPIEvalTarget) GetLastRunAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LastRunAt
}

func (p *PublicAPIEvalTarget) GetLastSkippedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LastSkippedAt
}

func (p *PublicAPIEvalTarget) GetSkipReason() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SkipReason
}

func (p *PublicAPIEvalTarget) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicAPIEvalTarget) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
