// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ace1cd775074

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceSkillsResponse struct {
	Data []PublicAPIPerformanceSkill `json:"data"`
	Meta map[string]any              `json:"meta,omitzero"`
}

func (p PublicAPIPerformanceSkillsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceSkillsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceSkillsResponse) GetData() []PublicAPIPerformanceSkill {
	if p == nil {
		return []PublicAPIPerformanceSkill{}
	}
	return p.Data
}

func (p *PublicAPIPerformanceSkillsResponse) GetMeta() map[string]any {
	if p == nil {
		return nil
	}
	return p.Meta
}
