// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceOperation struct {
	ID                 string                                                          `json:"id"`
	Method             string                                                          `json:"method"`
	Path               string                                                          `json:"path"`
	Description        optionalnullable.OptionalNullable[string]                       `json:"description,omitzero"`
	Category           optionalnullable.OptionalNullable[PublicAPIPerformanceCategory] `json:"category,omitzero"`
	OpenapiOperationID optionalnullable.OptionalNullable[string]                       `json:"openapi_operation_id,omitzero"`
	InterfaceID        optionalnullable.OptionalNullable[string]                       `json:"interface_id,omitzero"`
	CreatedAt          optionalnullable.OptionalNullable[string]                       `json:"created_at,omitzero"`
}

func (p PublicAPIPerformanceOperation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceOperation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceOperation) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceOperation) GetMethod() string {
	if p == nil {
		return ""
	}
	return p.Method
}

func (p *PublicAPIPerformanceOperation) GetPath() string {
	if p == nil {
		return ""
	}
	return p.Path
}

func (p *PublicAPIPerformanceOperation) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicAPIPerformanceOperation) GetCategory() optionalnullable.OptionalNullable[PublicAPIPerformanceCategory] {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *PublicAPIPerformanceOperation) GetOpenapiOperationID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.OpenapiOperationID
}

func (p *PublicAPIPerformanceOperation) GetInterfaceID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.InterfaceID
}

func (p *PublicAPIPerformanceOperation) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}
