// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 019c641b63dd

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicCustomEvalHistoryRun struct {
	ID             string                                     `json:"id"`
	Endpoint       PublicCustomEvalHistoryEndpoint            `json:"endpoint"`
	TargetKey      optionalnullable.OptionalNullable[string]  `json:"target_key,omitzero"`
	EvalType       optionalnullable.OptionalNullable[string]  `json:"eval_type,omitzero"`
	PromptSent     optionalnullable.OptionalNullable[string]  `json:"prompt_sent,omitzero"`
	Model          optionalnullable.OptionalNullable[string]  `json:"model,omitzero"`
	ModelType      optionalnullable.OptionalNullable[string]  `json:"model_type,omitzero"`
	Platform       optionalnullable.OptionalNullable[string]  `json:"platform,omitzero"`
	Passed         bool                                       `json:"passed"`
	Score          optionalnullable.OptionalNullable[float64] `json:"score,omitzero"`
	LatencyMs      optionalnullable.OptionalNullable[int64]   `json:"latency_ms,omitzero"`
	ToolCallCount  int64                                      `json:"tool_call_count"`
	ErrorMessage   optionalnullable.OptionalNullable[string]  `json:"error_message,omitzero"`
	IsInfraError   *bool                                      `default:"false" json:"is_infra_error"`
	RunAt          string                                     `json:"run_at"`
	HarnessLabel   optionalnullable.OptionalNullable[string]  `json:"harness_label,omitzero"`
	ModelLabel     optionalnullable.OptionalNullable[string]  `json:"model_label,omitzero"`
	RunContextSent map[string]any                             `json:"run_context_sent,omitzero"`
}

func (p PublicCustomEvalHistoryRun) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicCustomEvalHistoryRun) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicCustomEvalHistoryRun) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicCustomEvalHistoryRun) GetEndpoint() PublicCustomEvalHistoryEndpoint {
	if p == nil {
		return PublicCustomEvalHistoryEndpoint{}
	}
	return p.Endpoint
}

func (p *PublicCustomEvalHistoryRun) GetTargetKey() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.TargetKey
}

func (p *PublicCustomEvalHistoryRun) GetEvalType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.EvalType
}

func (p *PublicCustomEvalHistoryRun) GetPromptSent() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.PromptSent
}

func (p *PublicCustomEvalHistoryRun) GetModel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PublicCustomEvalHistoryRun) GetModelType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ModelType
}

func (p *PublicCustomEvalHistoryRun) GetPlatform() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PublicCustomEvalHistoryRun) GetPassed() bool {
	if p == nil {
		return false
	}
	return p.Passed
}

func (p *PublicCustomEvalHistoryRun) GetScore() optionalnullable.OptionalNullable[float64] {
	if p == nil {
		return nil
	}
	return p.Score
}

func (p *PublicCustomEvalHistoryRun) GetLatencyMs() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.LatencyMs
}

func (p *PublicCustomEvalHistoryRun) GetToolCallCount() int64 {
	if p == nil {
		return 0
	}
	return p.ToolCallCount
}

func (p *PublicCustomEvalHistoryRun) GetErrorMessage() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ErrorMessage
}

func (p *PublicCustomEvalHistoryRun) GetIsInfraError() *bool {
	if p == nil {
		return nil
	}
	return p.IsInfraError
}

func (p *PublicCustomEvalHistoryRun) GetRunAt() string {
	if p == nil {
		return ""
	}
	return p.RunAt
}

func (p *PublicCustomEvalHistoryRun) GetHarnessLabel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.HarnessLabel
}

func (p *PublicCustomEvalHistoryRun) GetModelLabel() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ModelLabel
}

func (p *PublicCustomEvalHistoryRun) GetRunContextSent() map[string]any {
	if p == nil {
		return nil
	}
	return p.RunContextSent
}
