// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1c2b8faa01bf

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicEvalConfigResponse struct {
	Models                        []string                                  `json:"models"`
	Targets                       []PublicAPIEvalTarget                     `json:"targets,omitzero"`
	EndpointIds                   []string                                  `json:"endpoint_ids"`
	CustomEvalIds                 []string                                  `json:"custom_eval_ids,omitzero"`
	EnvVars                       map[string]string                         `json:"env_vars,omitzero"`
	EnvProfiles                   []PublicEvalEnvProfileSummary             `json:"env_profiles,omitzero"`
	DefaultEnvProfileID           optionalnullable.OptionalNullable[string] `json:"default_env_profile_id,omitzero"`
	APIBaseURL                    optionalnullable.OptionalNullable[string] `json:"api_base_url,omitzero"`
	CanConfigurePerModelSchedules *bool                                     `default:"false" json:"can_configure_per_model_schedules"`
}

func (p PublicEvalConfigResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicEvalConfigResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicEvalConfigResponse) GetModels() []string {
	if p == nil {
		return []string{}
	}
	return p.Models
}

func (p *PublicEvalConfigResponse) GetTargets() []PublicAPIEvalTarget {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicEvalConfigResponse) GetEndpointIds() []string {
	if p == nil {
		return []string{}
	}
	return p.EndpointIds
}

func (p *PublicEvalConfigResponse) GetCustomEvalIds() []string {
	if p == nil {
		return nil
	}
	return p.CustomEvalIds
}

func (p *PublicEvalConfigResponse) GetEnvVars() map[string]string {
	if p == nil {
		return nil
	}
	return p.EnvVars
}

func (p *PublicEvalConfigResponse) GetEnvProfiles() []PublicEvalEnvProfileSummary {
	if p == nil {
		return nil
	}
	return p.EnvProfiles
}

func (p *PublicEvalConfigResponse) GetDefaultEnvProfileID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.DefaultEnvProfileID
}

func (p *PublicEvalConfigResponse) GetAPIBaseURL() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.APIBaseURL
}

func (p *PublicEvalConfigResponse) GetCanConfigurePerModelSchedules() *bool {
	if p == nil {
		return nil
	}
	return p.CanConfigurePerModelSchedules
}
