// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f21bc7617e23

package components

type PublicAPIPerformanceTextModel struct {
	ID              string                         `json:"id"`
	Label           string                         `json:"label"`
	Platform        string                         `json:"platform"`
	CostPer1mInput  float64                        `json:"cost_per_1m_input"`
	CostPer1mOutput float64                        `json:"cost_per_1m_output"`
	Target          PublicAPIPerformanceTargetSpec `json:"target"`
}

func (p *PublicAPIPerformanceTextModel) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceTextModel) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PublicAPIPerformanceTextModel) GetPlatform() string {
	if p == nil {
		return ""
	}
	return p.Platform
}

func (p *PublicAPIPerformanceTextModel) GetCostPer1mInput() float64 {
	if p == nil {
		return 0.0
	}
	return p.CostPer1mInput
}

func (p *PublicAPIPerformanceTextModel) GetCostPer1mOutput() float64 {
	if p == nil {
		return 0.0
	}
	return p.CostPer1mOutput
}

func (p *PublicAPIPerformanceTextModel) GetTarget() PublicAPIPerformanceTargetSpec {
	if p == nil {
		return PublicAPIPerformanceTargetSpec{}
	}
	return p.Target
}
