// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 29bfc26b6370

package components

type PublicUpdateActionRequest struct {
	Status        *string `json:"status,omitzero"`
	OwnerUserID   *string `json:"owner_user_id,omitzero"`
	IgnoredReason *string `json:"ignored_reason,omitzero"`
	Note          *string `json:"note,omitzero"`
}

func (p *PublicUpdateActionRequest) GetStatus() *string {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PublicUpdateActionRequest) GetOwnerUserID() *string {
	if p == nil {
		return nil
	}
	return p.OwnerUserID
}

func (p *PublicUpdateActionRequest) GetIgnoredReason() *string {
	if p == nil {
		return nil
	}
	return p.IgnoredReason
}

func (p *PublicUpdateActionRequest) GetNote() *string {
	if p == nil {
		return nil
	}
	return p.Note
}
