// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceCategory struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	SortOrder *int64 `default:"0" json:"sort_order"`
}

func (p PublicAPIPerformanceCategory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceCategory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceCategory) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceCategory) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicAPIPerformanceCategory) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PublicAPIPerformanceCategory) GetSortOrder() *int64 {
	if p == nil {
		return nil
	}
	return p.SortOrder
}
