// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicAPIPerformanceUseCase struct {
	ID          string                                                          `json:"id"`
	Prompt      string                                                          `json:"prompt"`
	Description optionalnullable.OptionalNullable[string]                       `json:"description,omitzero"`
	Category    optionalnullable.OptionalNullable[PublicAPIPerformanceCategory] `json:"category,omitzero"`
	CreatedAt   optionalnullable.OptionalNullable[string]                       `json:"created_at,omitzero"`
}

func (p PublicAPIPerformanceUseCase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIPerformanceUseCase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIPerformanceUseCase) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublicAPIPerformanceUseCase) GetPrompt() string {
	if p == nil {
		return ""
	}
	return p.Prompt
}

func (p *PublicAPIPerformanceUseCase) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicAPIPerformanceUseCase) GetCategory() optionalnullable.OptionalNullable[PublicAPIPerformanceCategory] {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *PublicAPIPerformanceUseCase) GetCreatedAt() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}
