// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6d8feb7f1e04

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type PublicPromptEvalRunRequest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"prompts" json:"type"`
	// Prompt IDs to run. Omit to run all active prompts.
	PromptIds optionalnullable.OptionalNullable[[]string] `json:"prompt_ids,omitzero"`
	// Explicit prompt targets. Omit to use configured scheduled prompt targets.
	Targets optionalnullable.OptionalNullable[[]PublicPromptEvalRunTarget] `json:"targets,omitzero"`
	// If true, re-run even when the prompt/platform/model has already run today.
	Force *bool `default:"false" json:"force"`
}

func (p PublicPromptEvalRunRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicPromptEvalRunRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicPromptEvalRunRequest) GetType() string {
	return "prompts"
}

func (p *PublicPromptEvalRunRequest) GetPromptIds() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.PromptIds
}

func (p *PublicPromptEvalRunRequest) GetTargets() optionalnullable.OptionalNullable[[]PublicPromptEvalRunTarget] {
	if p == nil {
		return nil
	}
	return p.Targets
}

func (p *PublicPromptEvalRunRequest) GetForce() *bool {
	if p == nil {
		return nil
	}
	return p.Force
}
