// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3a32540b6d38

package components

type PublicOkResponse struct {
	Ok bool `json:"ok"`
}

func (p *PublicOkResponse) GetOk() bool {
	if p == nil {
		return false
	}
	return p.Ok
}
