// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4ff1c95c95d9

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type UpdatePublicPromptRequest struct {
	Text        *string                                     `json:"text,omitzero"`
	TopicID     *string                                     `json:"topic_id,omitzero"`
	PlatformIds optionalnullable.OptionalNullable[[]string] `json:"platform_ids,omitzero"`
	IsActive    *bool                                       `json:"is_active,omitzero"`
}

func (u UpdatePublicPromptRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePublicPromptRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePublicPromptRequest) GetText() *string {
	if u == nil {
		return nil
	}
	return u.Text
}

func (u *UpdatePublicPromptRequest) GetTopicID() *string {
	if u == nil {
		return nil
	}
	return u.TopicID
}

func (u *UpdatePublicPromptRequest) GetPlatformIds() optionalnullable.OptionalNullable[[]string] {
	if u == nil {
		return nil
	}
	return u.PlatformIds
}

func (u *UpdatePublicPromptRequest) GetIsActive() *bool {
	if u == nil {
		return nil
	}
	return u.IsActive
}
