// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdatePromptTopicRequest struct {
	Name string `json:"name"`
}

func (u *UpdatePromptTopicRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}
