// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type UpdatePublicAPIPerformanceUseCaseRequest struct {
	Prompt       optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
	CategoryName optionalnullable.OptionalNullable[string] `json:"category_name,omitzero"`
	Description  optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
}

func (u *UpdatePublicAPIPerformanceUseCaseRequest) GetPrompt() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Prompt
}

func (u *UpdatePublicAPIPerformanceUseCaseRequest) GetCategoryName() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.CategoryName
}

func (u *UpdatePublicAPIPerformanceUseCaseRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Description
}
