// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9df4e71ec31d

package components

type UpdatePromptTopicRequest struct {
	Name string `json:"name"`
}

func (u *UpdatePromptTopicRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}
