// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
)

type UpdatePublicAPIPerformanceOperationRequest struct {
	Method             optionalnullable.OptionalNullable[string] `json:"method,omitzero"`
	Path               optionalnullable.OptionalNullable[string] `json:"path,omitzero"`
	Description        optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	CategoryName       optionalnullable.OptionalNullable[string] `json:"category_name,omitzero"`
	CategorySlug       optionalnullable.OptionalNullable[string] `json:"category_slug,omitzero"`
	OpenapiOperationID optionalnullable.OptionalNullable[string] `json:"openapi_operation_id,omitzero"`
	InterfaceID        optionalnullable.OptionalNullable[string] `json:"interface_id,omitzero"`
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetMethod() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Method
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetPath() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Path
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetCategoryName() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.CategoryName
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetCategorySlug() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.CategorySlug
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetOpenapiOperationID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.OpenapiOperationID
}

func (u *UpdatePublicAPIPerformanceOperationRequest) GetInterfaceID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.InterfaceID
}
