// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/usesapient/cli/internal/sdk/optionalnullable"
	"github.com/usesapient/cli/internal/sdk/sdkinternal/utils"
)

type UpdatePublicOperationPromptRequest struct {
	Prompt           optionalnullable.OptionalNullable[string]           `json:"prompt,omitzero"`
	ExpectedBehavior optionalnullable.OptionalNullable[string]           `json:"expected_behavior,omitzero"`
	Graders          optionalnullable.OptionalNullable[[]map[string]any] `json:"graders,omitzero"`
	ReferenceAnswer  optionalnullable.OptionalNullable[string]           `json:"reference_answer,omitzero"`
	Enabled          optionalnullable.OptionalNullable[bool]             `json:"enabled,omitzero"`
}

func (u UpdatePublicOperationPromptRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePublicOperationPromptRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePublicOperationPromptRequest) GetPrompt() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Prompt
}

func (u *UpdatePublicOperationPromptRequest) GetExpectedBehavior() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ExpectedBehavior
}

func (u *UpdatePublicOperationPromptRequest) GetGraders() optionalnullable.OptionalNullable[[]map[string]any] {
	if u == nil {
		return nil
	}
	return u.Graders
}

func (u *UpdatePublicOperationPromptRequest) GetReferenceAnswer() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ReferenceAnswer
}

func (u *UpdatePublicOperationPromptRequest) GetEnabled() optionalnullable.OptionalNullable[bool] {
	if u == nil {
		return nil
	}
	return u.Enabled
}
